const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'social-import-test-only-secret';
process.env.MONGOMS_RUNTIME_DOWNLOAD = 'false';
for (const key of ['GEMINI_API_KEY', 'SOCIAL_IMPORT_INSTAGRAM_ACCESS_TOKEN', 'SOCIAL_IMPORT_FACEBOOK_PAGE_TOKEN', 'R2_ACCOUNT_ID', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY', 'CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET']) delete process.env[key];
const { MongoMemoryServer } = require('mongodb-memory-server');
const mongoose = require('mongoose');
const express = require('express');
const ffmpeg = require('ffmpeg-static');
const SocialImport = require('../models/SocialProductImport');
const ProductDraft = require('../models/ProductDraft');
const Product = require('../models/Product');
const User = require('../models/User');
const Category = require('../models/Category');
const { generateToken } = require('../utils/generateToken');
const network = require('../modules/social-product-import/socialImport.network');
const service = require('../modules/social-product-import/socialImport.service');
const media = require('../modules/social-product-import/socialImport.media');
const { notFound, errorHandler } = require('../middleware/errorMiddleware');

test('social link import uses real media processing, draft persistence and publication', { timeout: 90000 }, async (t) => {
  const root = path.resolve(__dirname, '../../.tmp'); await fs.mkdir(root, { recursive: true });
  const directory = await fs.mkdtemp(path.join(root, 'social-integration-'));
  let mongo; let server; const jobIds = [];
  try {
    mongo = await MongoMemoryServer.create({ instance: { dbPath: directory, ip: '127.0.0.1' }, binary: { version: '7.0.14', systemBinary: process.platform === 'win32' ? path.resolve(__dirname, '../node_modules/.cache/mongodb-binaries/mongod-x64-win32-7.0.14.exe') : undefined } });
    await mongoose.connect(mongo.getUri(), { dbName: 'isolated_social_import_test', serverSelectionTimeoutMS: 10000 });
    assert.equal(mongoose.connection.name, 'isolated_social_import_test');
    await Promise.all([SocialImport.init(), ProductDraft.init(), Product.init(), User.init(), Category.init()]);
    const manager = await User.create({ name: 'Import test admin', phone: '9500000081', role: 'admin', activeMode: 'admin' });
    const other = await User.create({ name: 'Other import admin', phone: '9500000082', role: 'admin', activeMode: 'admin' });
    const customer = await User.create({ name: 'Import customer', phone: '9000000081', role: 'customer' });
    const token = generateToken(manager); const otherToken = generateToken(other);
    const category = await Category.create({ name: 'Sarees', slug: 'social-sarees' });
    const app = express(); app.use(express.json());
    app.use('/api/admin/social-imports', require('../modules/social-product-import/socialImport.routes'));
    app.use('/api/admin/product-drafts', require('../routes/productDraftRoutes'));
    const { protect } = require('../middleware/authMiddleware');
    const { adminOnly } = require('../middleware/adminMiddleware');
    app.use('/api/admin/products', protect, adminOnly, require('../routes/adminProductRoutes'));
    app.use('/api/admin/reel-imports', require('../modules/reel-product-import/reelImport.routes'));
    app.use(notFound); app.use(errorHandler);
    server = await new Promise((resolve) => { const listener = app.listen(0, '127.0.0.1', () => resolve(listener)); });
    const base = `http://127.0.0.1:${server.address().port}/api/admin`;
    const request = async (route, { method = 'GET', body, auth = token } = {}) => {
      const response = await fetch(base + route, { method, headers: { 'Content-Type': 'application/json', ...(auth ? { Authorization: 'Bearer ' + auth } : {}) }, body: body ? JSON.stringify(body) : undefined, signal: AbortSignal.timeout(10000) });
      return { status: response.status, data: await response.json() };
    };
    // Replace only Meta's external responses; image/video decoding, storage,
    // authentication, routing and MongoDB writes below are the real code.
    const photoPath = path.join(directory, 'source.jpg'); const videoPath = path.join(directory, 'source.mp4');
    await media.run(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=maroon:s=320x480', '-frames:v', '1', photoPath]);
    await media.run(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x480:rate=10:duration=2', '-pix_fmt', 'yuv420p', videoPath]);
    const photo = await fs.readFile(photoPath); const video = await fs.readFile(videoPath);
    let unavailable = false;
    t.mock.method(network, 'safeRead', async (url) => {
      if (unavailable) throw Object.assign(new Error('This post requires account access.'), { errorCode: 'SOCIAL_UNAVAILABLE' });
      if (url.includes('photo.jpg')) return { buffer: photo, contentType: 'image/jpeg', url };
      if (url.includes('video.mp4')) return { buffer: video, contentType: 'video/mp4', url };
      return { buffer: Buffer.from(`<meta property="og:description" content="Name: Wine Cotton Saree&#10;Fabric: Cotton&#10;Rs 1299"><meta property="og:image" content="https://scontent.fbcdn.net/photo.jpg">${url.includes('/reel/') ? '<meta property="og:video" content="https://video.fbcdn.net/video.mp4">' : ''}`), contentType: 'text/html', url };
    });
    const enqueue = t.mock.method(service, 'enqueue', () => {});
    let imported;
    await t.test('URL submission is protected and rejects unsupported sources', async () => {
      assert.equal((await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/ABC/' }, auth: '' })).status, 401);
      assert.equal((await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/ABC/' }, auth: generateToken(customer) })).status, 403);
      assert.equal((await request('/social-imports', { method: 'POST', body: { url: 'http://169.254.169.254/' } })).status, 400);
    });
    await t.test('a public post imports durable photos and caption details with no product publication', async () => {
      const response = await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/ABC/?igsh=tracking' } });
      assert.equal(response.status, 202); imported = response.data.data; jobIds.push(imported._id);
      assert.equal(enqueue.mock.callCount(), 1);
      await service.processImport(imported._id);
      const loaded = await request('/social-imports/' + imported._id);
      assert.equal(loaded.data.data.status, 'ready', loaded.data.data.error);
      imported = loaded.data.data;
      assert.equal(imported.suggestion.name, 'Wine Cotton Saree'); assert.equal(imported.suggestion.price, 1299);
      assert.equal(imported.suggestion.stock ?? null, null); assert.equal(imported.images.length, 1);
      assert.ok((await fs.stat(path.resolve(__dirname, '..' + imported.images[0].url))).size > 0);
      assert.equal(await Product.countDocuments(), 0); assert.equal(await ProductDraft.countDocuments(), 0);
      assert.equal(imported.runId, undefined); assert.equal(imported.sourceKey, undefined);
    });
    await t.test('the same canonical link reopens one import and other admins cannot access it', async () => {
      const duplicate = await request('/social-imports', { method: 'POST', body: { url: 'https://www.instagram.com/p/ABC/' } });
      assert.equal(duplicate.status, 200); assert.equal(duplicate.data.duplicate, true); assert.equal(duplicate.data.data._id, imported._id);
      assert.equal(await SocialImport.countDocuments(), 1);
      assert.equal((await request('/social-imports/' + imported._id, { auth: otherToken })).status, 404);
      assert.equal((await request('/social-imports', { auth: otherToken })).data.total, 0);
    });
    let draftId;
    await t.test('review saves edited details using only selected server-owned photos and retries are idempotent', async () => {
      const body = { name: 'Edited Wine Saree', imageIds: imported.images.map((image) => image.id), primaryImageId: imported.images[0].id, category: String(category._id), price: 1499, originalPrice: 1999, stock: 5, sizingMode: 'free-size', description: 'Reviewed product description' };
      const invalid = await request(`/social-imports/${imported._id}/draft`, { method: 'POST', body: { ...body, imageIds: ['fake'] } });
      assert.equal(invalid.status, 400);
      const saved = await request(`/social-imports/${imported._id}/draft`, { method: 'POST', body });
      assert.equal(saved.status, 201); draftId = saved.data.draftId;
      const draft = await ProductDraft.findById(draftId);
      assert.equal(draft.name, 'Edited Wine Saree'); assert.equal(draft.status, 'draft'); assert.equal(draft.images[0].url, imported.images[0].url);
      assert.equal(draft.sourceType, 'social-import'); assert.equal(String(draft.sourceSocialImportId), imported._id);
      const retry = await request(`/social-imports/${imported._id}/draft`, { method: 'POST', body: { ...body, name: 'Must not overwrite saved edits' } });
      assert.equal(retry.data.draftId, draftId); assert.equal(retry.data.duplicate, true);
      assert.equal(await ProductDraft.countDocuments(), 1); assert.equal(await Product.countDocuments(), 0);
    });
    await t.test('explicit publication creates one catalog product and repeated publishing does not duplicate it', async () => {
      const publish = await request('/product-drafts/publish-selected', { method: 'POST', body: { ids: [draftId] } });
      assert.equal(publish.status, 200, publish.data.message);
      assert.equal(await Product.countDocuments({ sourceDraftId: draftId }), 1);
      const product = await Product.findOne({ sourceDraftId: draftId });
      assert.equal(product.name, 'Edited Wine Saree'); assert.equal(product.stock, 5); assert.equal(product.price, 1499);
      await request('/product-drafts/publish-selected', { method: 'POST', body: { ids: [draftId] } });
      assert.equal(await Product.countDocuments(), 1);
    });
    await t.test('Facebook reels preserve video and extract selectable product stills', async () => {
      const response = await request('/social-imports', { method: 'POST', body: { url: 'https://facebook.com/reel/123/' } });
      const id = response.data.data._id; jobIds.push(id);
      await service.processImport(id);
      let reel = (await request('/social-imports/' + id)).data.data;
      assert.equal(reel.status, 'ready', reel.error); assert.equal(reel.videos.length, 1);
      const recheck = await request(`/social-imports/${id}/retry`, { method: 'POST', body: {} });
      assert.equal(recheck.status, 200); assert.equal(recheck.data.data.status, 'queued');
      await service.processImport(id);
      reel = (await request('/social-imports/' + id)).data.data;
      assert.equal(reel.status, 'ready', reel.error); assert.equal(reel.attempts, 2);
      assert.ok(reel.images.some((image) => image.kind === 'frame'));
      assert.ok(reel.images.filter((image) => image.kind === 'frame').every((image) => image.timestamp >= 0));
      const chosen = reel.images.find((image) => image.kind === 'frame' && image.recommendedCover);
      assert.ok(chosen && chosen.qualityScore > 0);
      assert.ok(reel.frameSelections[0].analyzedFrames > 0);
      const saved = await request(`/social-imports/${id}/draft`, {method:'POST',body:{name:'Editable Video Saree',category:String(category._id),price:1499,stock:4,sizingMode:'free-size',imageIds:[chosen.id],primaryImageId:chosen.id,viewTypes:{[chosen.id]:'side'},includeVideo:true}});
      assert.equal(saved.status,201,saved.data.message);
      const protectedDraft = await request(`/social-imports/${id}/retry`, { method: 'POST', body: {} });
      assert.equal(protectedDraft.status, 409);
      assert.equal((await SocialImport.findById(id)).status, 'ready');
      const updated = await request('/product-drafts/'+saved.data.draftId,{method:'PUT',body:{name:'Edited Video Saree',description:'Description edited after import'}});
      assert.equal(updated.status,200,updated.data.message);
      const published = await request('/product-drafts/publish-selected',{method:'POST',body:{ids:[saved.data.draftId]}});
      assert.equal(published.status,200,published.data.message);
      const product = await Product.findOne({sourceDraftId:saved.data.draftId});
      assert.equal(product.images[0].sourceFrame.viewType,'side');
      assert.equal(product.images[0].sourceFrame.timestampSeconds,chosen.timestamp);
      assert.equal(product.videos.length,1);
      const edited = await request('/products/'+product._id,{method:'PUT',body:{name:'Updated published video product',sku:product.sku,category:String(category._id),sizingMode:'free-size',price:1599,stock:7,images:product.images.map(image=>image.toObject()),videos:product.videos.map(video=>video.toObject())}});
      assert.equal(edited.status,200,edited.data.message);
      const reloaded = await Product.findById(product._id);
      assert.equal(reloaded.name,'Updated published video product');
      assert.equal(reloaded.stock,7); assert.equal(reloaded.images[0].sourceFrame.viewType,'side');
      assert.equal(reloaded.images[0].url,chosen.url); assert.equal(reloaded.videos.length,1);
    });
    await t.test('unavailable posts fail visibly and can be retried; cancelled jobs never publish', async () => {
      unavailable = true;
      const response = await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/BLOCKED/' } });
      const id = response.data.data._id; jobIds.push(id);
      await service.processImport(id);
      const failed = (await request('/social-imports/' + id)).data.data;
      assert.equal(failed.status, 'failed'); assert.equal(failed.errorCode, 'SOCIAL_UNAVAILABLE');
      unavailable = false;
      assert.equal((await request(`/social-imports/${id}/retry`, { method: 'POST', body: {} })).data.data.status, 'queued');
      assert.equal((await request(`/social-imports/${id}/cancel`, { method: 'POST', body: {} })).data.data.status, 'cancelled');
      await service.processImport(id);
      assert.equal((await SocialImport.findById(id)).status, 'cancelled');
      assert.equal((await request(`/social-imports/${id}/draft`, { method: 'POST', body: { name: 'Do not publish' } })).status, 409);
      assert.equal(await Product.countDocuments(), 2);
    });
    await t.test('uploaded reel drafts respect the chosen cover and reject an empty photo selection',async(st)=>{
      const ReelImport=require('../models/ReelImport');const ReelCandidate=require('../models/ReelCandidate');
      const reel=await ReelImport.create({createdBy:manager._id,sourceVideo:{provider:'r2',storageKey:'fixture/reel.mp4',originalFilename:'reel.mp4',mimeType:'video/mp4',sizeBytes:10,durationSeconds:5},status:'review_required'});
      const candidate=await ReelCandidate.create({job:reel._id,groupNumber:1,frames:[{provider:'r2',storageKey:'fixture/a.jpg',url:'https://example.test/a.jpg',selected:true,qualityScore:.9,timestampSeconds:1,selectionVersion:'quality-v1'},{provider:'r2',storageKey:'fixture/b.jpg',url:'https://example.test/b.jpg',selected:true,qualityScore:.85,timestampSeconds:3,viewType:'back',selectionVersion:'quality-v1'}],suggestions:{name:'Editable uploaded reel',sizingMode:'free-size'}});
      const photoId=String(candidate.frames[1]._id);
      const changed=await request(`/reel-imports/${reel._id}/candidates/${candidate._id}`,{method:'PATCH',body:{adminOverrides:{primaryFrameId:photoId},selectedFrameIds:candidate.frames.map(frame=>String(frame._id))}});
      assert.equal(changed.status,200);
      const created=await request(`/reel-imports/${reel._id}/create-drafts`,{method:'POST',body:{candidateIds:[String(candidate._id)]}});
      assert.equal(created.status,201,created.data.message);
      const draft=await ProductDraft.findOne({sourceCandidateId:candidate._id});
      assert.equal(draft.images[0].url,'https://example.test/b.jpg');assert.equal(draft.images[0].primary,true);assert.equal(draft.images[0].sourceFrame.viewType,'back');
      const empty=await ReelCandidate.create({job:reel._id,groupNumber:2,frames:[{url:'https://example.test/c.jpg',selected:false}],suggestions:{name:'No selected photo'}});
      const rejected=await request(`/reel-imports/${reel._id}/create-drafts`,{method:'POST',body:{candidateIds:[String(empty._id)]}});
      assert.equal(rejected.status,400);assert.match(rejected.data.message,/Select at least one product photo/);
      assert.equal(await ProductDraft.countDocuments({sourceCandidateId:empty._id}),0);
      const savedChange = await request(`/reel-imports/${reel._id}/candidates/${candidate._id}`, { method: 'PATCH', body: { adminOverrides: { name: 'Ready Reel Saree', category: String(category._id), price: 899, stock: 3, sizingMode: 'free-size' } } });
      assert.equal(savedChange.status, 200);
      await ProductDraft.updateOne({ _id: draft._id }, { $push: { images: { url: '/uploads/reel-added-later.webp', primary: false } } });
      const keepAddedPhoto = await request(`/reel-imports/${reel._id}/candidates/${candidate._id}`, { method: 'PATCH', body: { selectedFrameIds: [photoId], adminOverrides: { primaryFrameId: photoId } } });
      assert.equal(keepAddedPhoto.status, 200);
      const draftForPublish = await ProductDraft.findById(draft._id);
      assert.equal(draftForPublish.name, 'Ready Reel Saree'); assert.equal(draftForPublish.price, 899);
      assert.equal(draftForPublish.images.length, 2); assert.equal(draftForPublish.images[1].url, '/uploads/reel-added-later.webp');
      process.env.GEMINI_API_KEY = 'isolated-reel-analysis-key';
      st.after(() => { delete process.env.GEMINI_API_KEY; });
      const realFetch = global.fetch;
      st.mock.method(global, 'fetch', async (url, options) => String(url).startsWith('https://example.test/') ? new Response(photo, { headers: { 'Content-Type': 'image/jpeg' } }) : realFetch(url, options));
      st.mock.method(require('../services/mediaStorage.service'), 'downloadObject', async () => { throw new Error('Fixture original unavailable'); });
      const context = st.mock.method(require('../services/productImportContext.service'), 'analyzeProductContext', async () => ({ contextStatus: 'failed', contextErrorCode: 'AI_QUOTA_EXCEEDED', contextError: 'The Gemini quota is currently exhausted.' }));
      const analyzed = await request(`/reel-imports/${reel._id}/candidates/${candidate._id}/analyze`, { method: 'POST', body: { selectedFrameIds: [photoId] } });
      assert.equal(analyzed.status, 200, analyzed.data.message);
      assert.equal(analyzed.data.data.analysis.errorCode, 'AI_QUOTA_EXCEEDED');
      assert.equal(analyzed.data.data.suggestions.name, 'Editable uploaded reel');
      assert.equal(analyzed.data.data.adminOverrides.name, 'Ready Reel Saree');
      assert.equal(analyzed.data.data.adminOverrides.price, 899);
      assert.equal(analyzed.data.data.savedDraft.name, 'Ready Reel Saree');
      const failedRefresh = await ReelCandidate.findById(candidate._id);
      assert.equal(failedRefresh.analysis.errorCode, 'AI_QUOTA_EXCEEDED');
      assert.equal(failedRefresh.audit.at(-1).details.errorCode, 'AI_QUOTA_EXCEEDED');
      assert.equal(context.mock.callCount(), 1);
      assert.equal((await ProductDraft.findById(draft._id)).price, 899);
      const publish = await request('/product-drafts/publish-selected', { method: 'POST', body: { ids: [String(draft._id)] } });
      assert.equal(publish.status, 200, publish.data.message);
      const again = await request('/product-drafts/publish-selected', { method: 'POST', body: { ids: [String(draft._id)] } });
      assert.equal(again.status, 200); assert.equal(await Product.countDocuments({ sourceDraftId: draft._id }), 1);
      assert.equal((await request(`/reel-imports/${reel._id}/candidates/${candidate._id}`, { method: 'PATCH', body: { adminOverrides: { price: 1 } } })).status, 409);
    });

    await t.test('one-screen publication validates essentials and creates one editable product', async () => {
      const created = await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/DIRECT/' } });
      const id = created.data.data._id; jobIds.push(id); await service.processImport(id);
      const job = (await request('/social-imports/' + id)).data.data;
      assert.equal(job.suggestion.category, String(category._id)); assert.equal(job.suggestion.price, 1299);
      const body = { ...job.suggestion, imageIds: job.images.map((image) => image.id), primaryImageId: job.images[0].id, stock: '' };
      const missing = await request(`/social-imports/${id}/publish`, { method: 'POST', body });
      assert.equal(missing.status, 400); assert.match(missing.data.message, /stock/);
      assert.equal(await ProductDraft.countDocuments({ sourceSocialImportId: id }), 0);
      assert.equal((await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...body, stock: 4 }, auth: otherToken })).status, 404);
      const published = await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...body, stock: 4 } });
      assert.equal(published.status, 200, published.data.message); assert.ok(published.data.productId);
      const product = await Product.findById(published.data.productId);
      assert.equal(product.price, 1299); assert.equal(product.stock, 4); assert.equal(product.images[0].url, job.images[0].url);
      const duplicate = await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...body, stock: 9, price: 1 } });
      assert.equal(duplicate.data.productId, published.data.productId); assert.equal(duplicate.data.duplicate, true);
      assert.equal(await Product.countDocuments({ sourceDraftId: published.data.draftId }), 1);
      assert.equal((await Product.findById(product._id)).price, 1299);
      assert.equal((await request('/social-imports/' + id)).data.data.publishedProductId, String(product._id));
    });

    await t.test('saved reviews resume in place and stale requests cannot overwrite draft edits', async () => {
      const created = await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/RESUME/' } });
      const id = created.data.data._id; jobIds.push(id); await service.processImport(id);
      const job = (await request('/social-imports/' + id)).data.data;
      const body = { ...job.suggestion, imageIds: job.images.map((image) => image.id), stock: '' };
      const saved = await request(`/social-imports/${id}/review`, { method: 'POST', body });
      assert.equal(saved.status, 200, saved.data.message);
      const old = saved.data.data.savedReview;
      assert.ok(old.draftUpdatedAt); assert.equal(saved.data.data.draftId, saved.data.draftId);
      const draft = await ProductDraft.findById(saved.data.draftId);
      draft.name = 'Name edited in drafts'; draft.images.push({ url: '/uploads/manually-added.webp', primary: false }); await draft.save();
      const stale = await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...old, stock: 3 } });
      assert.equal(stale.status, 409);
      const resumed = (await request('/social-imports/' + id)).data.data;
      assert.equal(resumed.savedReview.name, 'Name edited in drafts'); assert.equal(resumed.savedReview.imageIds.length, 2);
      const published = await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...resumed.savedReview, stock: 3 } });
      assert.equal(published.status, 200, published.data.message);
      const product = await Product.findById(published.data.productId);
      assert.equal(product.name, 'Name edited in drafts'); assert.equal(product.images.length, 2);
      assert.equal(product.images[1].url, '/uploads/manually-added.webp');
    });

    await t.test('sized products can provide their complete chart directly in import review', async () => {
      const created = await request('/social-imports', { method: 'POST', body: { url: 'https://instagram.com/p/SIZED/' } });
      const id = created.data.data._id; jobIds.push(id); await service.processImport(id);
      const job = (await request('/social-imports/' + id)).data.data;
      const kurti = await Category.create({ name: 'Kurtis', slug: 'context-kurtis' });
      const body = { name: 'Wine Cotton Kurti', category: String(kurti._id), price: 999, stock: 3, sizingMode: 'sized', sizes: ['M'], imageIds: job.images.map((image) => image.id) };
      const incomplete = await request(`/social-imports/${id}/publish`, { method: 'POST', body });
      assert.equal(incomplete.status, 400); assert.match(incomplete.data.message, /size chart/);
      const published = await request(`/social-imports/${id}/publish`, { method: 'POST', body: { ...body, sizeChart: { unit: 'in', rows: [{ size: 'M', bust: 38, chest: 38, waist: 34, frontLength: 30, hips: 40, acrossShoulder: 15 }] } } });
      assert.equal(published.status, 200, published.data.message);
      assert.equal((await Product.findById(published.data.productId)).sizeChart.rows[0].bust, 38);
    });
  } finally {
    if (server) await new Promise((resolve) => server.close(resolve));
    await mongoose.disconnect(); if (mongo) await mongo.stop();
    const uploadDir = path.resolve(__dirname, '../uploads');
    for (const name of await fs.readdir(uploadDir).catch(() => [])) if (jobIds.some((id) => name.startsWith('social-' + id + '-')) && /^[a-z\d-]+\.(webp|mp4)$/.test(name)) await fs.unlink(path.join(uploadDir, name));
    if (path.dirname(path.resolve(directory)) === root && path.basename(directory).startsWith('social-integration-')) await fs.rm(directory, { recursive: true, force: true });
  }
});
