const router = require('express').Router();
const rateLimit = require('express-rate-limit');
const coupon = require('../controllers/couponController');
const { optionalProtect, protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const previewLimiter = rateLimit({ windowMs: 60 * 1000, max: 60, standardHeaders: true, legacyHeaders: false });
router.get('/', coupon.getCoupons);
router.get('/stats', protect, adminOnly, coupon.getCouponStats);
router.get('/code-availability', protect, adminOnly, coupon.checkCouponCode);
router.get('/options', protect, adminOnly, coupon.searchCouponOptions);
router.post('/bulk', protect, adminOnly, coupon.bulkCouponAction);
router.post('/available', previewLimiter, optionalProtect, coupon.getAvailableCoupons);
router.post('/apply', previewLimiter, optionalProtect, coupon.applyCoupon);
router.get('/:id/insights', protect, adminOnly, coupon.getCouponInsights);
router.get('/:id/export', protect, adminOnly, coupon.exportCouponRedemptions);
router.post('/:id/simulate', protect, adminOnly, coupon.simulateCoupon);
router.post('/:id/duplicate', protect, adminOnly, coupon.duplicateCoupon);
router.patch('/:id/status', protect, adminOnly, coupon.updateCouponStatus);
router.patch('/:id/archive', protect, adminOnly, coupon.archiveCoupon);
router.patch('/:id/restore', protect, adminOnly, coupon.restoreCoupon);
router.post('/', protect, adminOnly, coupon.createCoupon);
router.put('/:id', protect, adminOnly, coupon.updateCoupon);
router.delete('/:id', protect, adminOnly, coupon.deleteCoupon);
module.exports = router;
