const router = require('express').Router();
const order = require('../controllers/orderController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const delivery = require('../controllers/deliveryController');
const fraud = require('../controllers/fraudProtectionController');
const rateLimit = require('express-rate-limit');
const evidenceUploadLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 20, standardHeaders: true, legacyHeaders: false });
const codOtpSendLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 5, standardHeaders: true, legacyHeaders: false });
const codOtpVerifyLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 10, standardHeaders: true, legacyHeaders: false });
router.post('/evidence/uploads', protect, adminOnly, evidenceUploadLimiter, fraud.evidenceUploadMiddleware, fraud.uploadEvidence);
router.get('/item-verification/:uniqueItemId', protect, adminOnly, fraud.verifyItemIdentity);
router.get('/:id/delivery', protect, delivery.details);
router.get('/:id/delivery/label', protect, adminOnly, delivery.label);
router.post('/:id/delivery/:action', protect, adminOnly, delivery.action);
router.post('/', protect, order.createOrder);
router.post('/cod', protect, order.createCodOrder);
router.post('/quote', protect, order.quoteOrder);
router.post('/:id/cod-verification/send', protect, codOtpSendLimiter, order.sendCodVerification);
router.post('/:id/cod-verification/verify', protect, codOtpVerifyLimiter, order.verifyCodVerification);
router.get('/', protect, adminOnly, order.adminOrders);
router.get('/workspace-summary', protect, adminOnly, order.orderWorkspaceSummary);
router.get('/:id/receipt', protect, order.receipt);
router.post('/:id/item-identities/generate', protect, adminOnly, fraud.generateItemIdentities);
router.post('/:id/packing/verify', protect, adminOnly, fraud.verifyPacking);
router.get('/:id/verification-evidence', protect, adminOnly, fraud.getEvidence);
router.put('/:id/status', protect, adminOnly, order.updateOrderStatus);
router.put('/:id/payment-status', protect, adminOnly, order.updatePaymentStatus);
router.patch('/:id/staff-notes', protect, adminOnly, order.addStaffNote);
router.put('/:id/shipping-address', protect, adminOnly, order.updateShippingAddress);
router.put('/:id/shipment', protect, adminOnly, order.updateShipment);
router.delete('/:id', protect, adminOnly, order.deleteOrder);
router.post('/:id/cancel', protect, order.cancelOrder);
router.post('/:id/items/:itemId/cancel', protect, order.cancelOrderItem);
router.post('/:id/cancellation-refund', protect, adminOnly, order.retryCancellationRefund);
router.post('/:id/item-cancellation-refund', protect, adminOnly, order.retryItemCancellationRefund);
router.post('/:id/rto/inspect', protect, adminOnly, order.inspectRto);
router.post('/:id/rto/refund', protect, adminOnly, order.retryRtoRefund);
router.get('/my-orders', protect, order.myOrders);
router.get('/admin/all', protect, adminOnly, order.adminOrders);
router.get('/admin/workspace-summary', protect, adminOnly, order.orderWorkspaceSummary);
router.get('/admin/:id', protect, adminOnly, order.getOrder);
router.get('/admin/:id/receipt', protect, adminOnly, order.receipt);
router.put('/admin/:id/status', protect, adminOnly, order.updateOrderStatus);
router.put('/admin/:id/payment-status', protect, adminOnly, order.updatePaymentStatus);
router.get('/:id', protect, order.getOrder);
module.exports = router;
