const express = require('express');
const rateLimit = require('express-rate-limit');
const C = require('../controllers/rentalController');
const { protect } = require('../middleware/authMiddleware');
const limiter = rateLimit({ windowMs: 60000, limit: 60, standardHeaders: 'draft-7', legacyHeaders: false });
const proofLimit = rateLimit({ windowMs: 60000, limit: 10, standardHeaders: true, legacyHeaders: false });
const proofUpload = require('../middleware/photoUploadMiddleware').createPhotoUpload({ files: 4, fields: 6,
  maxFileBytes: require('../services/photoCompressionService').PHOTO_PRIVATE_MAX_BYTES }).array('images', 4);
function customerRouter() {
  const router = express.Router();
  router.use(limiter);
  router.get('/configuration', C.configuration);
  router.get('/payment-methods', C.paymentMethods);
  router.get('/catalogue', C.catalogue);
  router.get('/availability', C.availability);
  router.get('/availability/:id/alternatives', C.alternatives);
  router.get('/slots', C.slots);
  router.get('/products/:id', C.listings);
  router.get('/calendar/:id', C.calendar);
  router.post('/calendar', C.calendarSet);
  router.post('/quote', C.quote);
  router.use(protect);
  router.get('/waitlist', C.waitlist);
  router.get('/waitlist/:id', C.waitlistDetail);
  router.post('/waitlist', C.joinWaitlist);
  router.post('/waitlist/:id/cancel', C.cancelWaitlist);
  router.get('/bookings', C.list);
  router.post('/bookings', C.hold);
  router.get('/bookings/recover/:attemptId', C.recoverHold);
  router.get('/bookings/:id', C.detail);
  router.post('/bookings/:id/requests', C.request);
  router.post('/bookings/:id/payment', C.payment);
  router.post('/bookings/:id/verify', C.verify);
  router.get('/bookings/:id/proofs', C.proofs);
  router.get('/bookings/:id/proofs/:photoId', C.proofPhoto);
  router.post('/bookings/:id/acknowledgements', C.acknowledge);
  router.get('/bookings/:id/couriers', C.couriers);
  return router;
}
function staffRouter() {
  const router = express.Router();
  router.use(protect, limiter, C.staffPermission('orders.read'), (req, _res, next) => { req.rentalStaff = true; next(); });
  router.get('/', C.workspace);
  router.get('/catalogue', C.catalogue);
  router.get('/availability', C.availability);
  router.get('/availability/:id/alternatives', C.alternatives);
  router.get('/slots', C.slots);
  router.get('/waitlist', C.waitlist);
  router.get('/tasks', C.staffPermission('inventory.read'), C.tasks);
  router.get('/readiness-queue', C.staffPermission('inventory.read'), C.readinessQueue);
  router.get('/setup/:id', C.staffPermission('inventory.read'), C.setup);
  router.post('/setup/:id/pieces', C.staffPermission('inventory.write'), C.registerPieces);
  router.get('/timeline', C.staffPermission('inventory.read'), C.timeline);
  router.get('/daily-desk', C.dailyDesk);
  router.post('/calendar', C.calendarSet);
  router.post('/tasks', C.staffPermission('inventory.write'), C.createTask);
  router.post('/tasks/:id', C.staffPermission('inventory.write'), C.updateTask);
  router.get('/refund-queue', C.staffPermission('returns.refund'), C.refundQueue);
  router.get('/piece-report', C.staffPermission('reports.read'), C.pieceReport);
  router.get('/bookings/:id/measurements', C.staffPermission('inventory.write'), C.measurements);
  router.post('/bookings/:id/measurements', C.staffPermission('inventory.write'), C.saveMeasurements);
  router.post('/quote', C.staffPermission('orders.write'), C.quote);
  router.get('/manage/:kind(products|assets|listings)', C.staffPermission('inventory.read'), C.managementRows);
  router.get('/report', C.staffPermission('reports.read'), C.report);
  router.get('/configuration', C.configuration);
  router.put('/configuration', C.staffPermission('settings.write', { ownerOnly: true }), C.saveConfiguration);
  router.post('/jobs/:id/retry', C.staffPermission('settings.write', { ownerOnly: true }), C.retry);
  router.get('/bookings', C.list);
  router.post('/bookings', C.staffPermission('orders.write'), C.counterHold);
  router.get('/bookings/:id', C.detail);
  router.post('/listings', C.staffPermission('inventory.write'), C.saveListing);
  router.get('/bookings/:id/payments', C.staffPermission('returns.refund'), C.payments);
  router.post('/bookings/:id/payments/:paymentId/reconcile', C.staffPermission('returns.refund'), C.recoverPayment);
  router.post('/assets', C.staffPermission('inventory.write'), C.saveAsset);
  router.post('/assets/:id/status', C.staffPermission('inventory.write'), C.changeAsset);
  router.post('/assets/:id/convert-to-sale', C.staffPermission('inventory.write', { ownerOnly: true }), C.convertAsset);
  router.get('/bookings/:id/proofs', C.proofs);
  router.get('/bookings/:id/proofs/:photoId', C.proofPhoto);
  router.post('/bookings/:id/proofs', C.staffPermission('returns.qc'), proofLimit, proofUpload, C.uploadProof);
  router.delete('/bookings/:id/proofs/:photoId', C.staffPermission('returns.qc'), C.withdrawProof);
  router.get('/bookings/:id/couriers', C.couriers);
  router.get('/bookings/:id/courier/:direction(outbound|inbound)/label', C.courierLabel);
  router.post('/bookings/:id/courier/:direction(outbound|inbound)/:action(book|pickup|cancel|sync|reconcile)', (req, res, next) => C.staffPermission('orders.write', { ownerOnly: req.params.action === 'reconcile' })(req, res, next), C.courier);
  router.post('/blocks', C.staffPermission('inventory.write'), C.block);
  router.delete('/blocks/:id', C.staffPermission('inventory.write'), C.releaseBlock);
  router.post('/bookings/:id/collection', C.staffPermission('returns.refund'), C.collect);
  router.post('/bookings/:id/operation', (req, res, next) => C.staffPermission(['ASSESS', 'WAIVE_ASSESSMENT', 'REOPEN_SETTLEMENT'].includes(req.body.action) ? 'returns.refund' : ['RECEIVE', 'INSPECT', 'RELEASE', 'DECLARE_LOST'].includes(req.body.action) ? 'returns.qc' : 'orders.write')(req, res, next), C.operation);
  router.post('/bookings/:id/reschedule', C.staffPermission('orders.write'), C.reschedule);
  router.post('/bookings/:id/replace', C.staffPermission('orders.write'), C.replace);
  router.post('/bookings/:id/cancel-items', C.staffPermission('returns.refund'), C.cancelItems);
  router.post('/bookings/:id/resolve', C.staffPermission('orders.write'), C.resolve);
  router.post('/bookings/:id/refund', C.staffPermission('returns.refund'), C.refund);
  return router;
}
module.exports = { customerRouter, staffRouter };
