const router = require('express').Router();
const returns = require('../controllers/returnController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const delivery = require('../controllers/deliveryController');
const returnUpload = require('../controllers/returnUploadController');
const rateLimit = require('express-rate-limit');
const reverse = (req, res, next) => { req.deliveryReturn = true; next(); };
const replacement = (req, res, next) => { req.deliveryReplacement = true; next(); };
const uploadLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 12, standardHeaders: true, legacyHeaders: false });
const fraud = require('../controllers/fraudProtectionController');
router.post('/evidence/uploads', protect, uploadLimiter, fraud.evidenceUploadMiddleware, fraud.uploadEvidence);
router.post('/uploads', protect, uploadLimiter, returnUpload.middleware, returnUpload.uploadReturnEvidence);
router.get('/my-requests', protect, returns.myReturns);
router.get('/order/:orderId', protect, returns.orderReturns);
router.patch('/:id/cancel', protect, returns.cancelMyReturn);
router.get('/:id/delivery', protect, reverse, delivery.details);
router.get('/:id/delivery/label', protect, adminOnly, reverse, delivery.label);
router.post('/:id/delivery/:action', protect, adminOnly, reverse, delivery.action);
router.get('/:id/replacement-delivery', protect, replacement, delivery.details);
router.get('/:id/replacement-delivery/label', protect, adminOnly, replacement, delivery.label);
router.post('/:id/replacement-delivery/:action', protect, adminOnly, replacement, delivery.action);
router.post('/', protect, returns.createReturn);
router.get('/stats', protect, adminOnly, returns.adminReturnStats);
router.get('/admin/all', protect, adminOnly, returns.adminReturns);
router.get('/', protect, adminOnly, returns.adminReturns);
router.put('/admin/:id/status', protect, adminOnly, returns.updateReturnStatus);
router.post('/admin/:id/inspect', protect, adminOnly, fraud.inspectReturn);
router.post('/admin/:id/decision', protect, adminOnly, fraud.decideReturn);
router.post('/admin/:id/refund/retry', protect, adminOnly, returns.retryReturnRefund);
router.post('/admin/:id/refund/reconcile', protect, adminOnly, returns.reconcileReturnRefund);
router.post('/admin/:id/exchange-adjustment/prepare', protect, adminOnly, returns.prepareExchangeAdjustment);
router.get('/admin/:id/refund-destination', protect, adminOnly, returns.revealRefundDestination);
router.patch('/admin/:id/meta', protect, adminOnly, returns.updateReturnMeta);
router.post('/:id/refund/retry', protect, adminOnly, returns.retryReturnRefund);
router.post('/:id/refund/reconcile', protect, adminOnly, returns.reconcileReturnRefund);
router.post('/:id/exchange-adjustment/prepare', protect, adminOnly, returns.prepareExchangeAdjustment);
router.get('/:id/refund-destination', protect, adminOnly, returns.revealRefundDestination);
router.patch('/:id/meta', protect, adminOnly, returns.updateReturnMeta);
router.put('/:id/status', protect, adminOnly, returns.updateReturnStatus);
router.post('/:id/inspect', protect, adminOnly, fraud.inspectReturn);
router.post('/:id/decision', protect, adminOnly, fraud.decideReturn);
router.get('/:id', protect, adminOnly, returns.getReturnDetail);
module.exports = router;
