const router = require('express').Router();
const rateLimit = require('express-rate-limit');
const review = require('../controllers/reviewController');
const reviewUpload = require('../controllers/reviewUploadController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const reviewActionLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 60, standardHeaders: true, legacyHeaders: false });
const reviewUploadLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 12, standardHeaders: true, legacyHeaders: false });
router.get('/', protect, adminOnly, review.adminReviews);
router.get('/management/stats', protect, adminOnly, review.adminReviewStats);
router.get('/management/options', protect, adminOnly, review.adminReviewOptions);
router.get('/management/export', protect, adminOnly, review.adminReviewExport);
router.post('/management/bulk', protect, adminOnly, review.bulkReviewAction);
router.post('/management/reminders', protect, adminOnly, review.sendReviewRequests);
router.get('/management/:id', protect, adminOnly, review.adminReviewDetail);
router.patch('/management/:id/moderation', protect, adminOnly, review.moderateReview);
router.patch('/management/:id/archive', protect, adminOnly, review.archiveReview);
router.patch('/management/:id/restore', protect, adminOnly, review.restoreReview);
router.patch('/management/:id/featured', protect, adminOnly, review.setFeatured);
router.put('/management/:id/reply', protect, adminOnly, review.replyToReview);
router.delete('/management/:id/reply', protect, adminOnly, review.deleteReply);
router.delete('/management/:id', protect, adminOnly, review.deleteReview);
router.get('/admin/all', protect, adminOnly, review.adminReviews);
router.patch('/admin/:id/visibility', protect, adminOnly, review.toggleVisibility);
router.delete('/admin/:id', protect, adminOnly, review.deleteReview);
router.get('/featured', review.featuredReviews);
router.post('/uploads', protect, reviewUploadLimiter, reviewUpload.middleware, reviewUpload.uploadReviewPhotos);
router.patch('/:id/visibility', protect, adminOnly, review.toggleVisibility);
router.delete('/:id', protect, adminOnly, review.deleteReview);
router.get('/:productId/summary', review.getReviewSummary);
router.get('/:productId/eligibility', protect, review.getReviewEligibility);
router.post('/:id/helpful', protect, reviewActionLimiter, review.toggleHelpful);
router.post('/:id/report', protect, reviewActionLimiter, review.reportReview);
router.patch('/:id/withdraw', protect, reviewActionLimiter, review.withdrawMyReview);
router.post('/:productId', protect, reviewActionLimiter, review.createReview);
router.get('/:productId/mine', protect, review.getMyReview);
router.put('/:id', protect, reviewActionLimiter, review.updateReview);
router.get('/:productId', review.getReviews);
module.exports = router;
