const router = require('express').Router();
const product = require('../controllers/productController');
const smartFill = require('../controllers/productSmartFillController');
const order = require('../controllers/orderController');
const coupon = require('../controllers/couponController');
const banner = require('../controllers/bannerController');
const campaign = require('../controllers/campaignController');
const category = require('../controllers/categoryController');
const review = require('../controllers/reviewController');
const returns = require('../controllers/returnController');
const dashboard = require('../controllers/dashboardController');
const contact = require('../controllers/contactController');
const newsletter = require('../controllers/newsletterController');
const crm = require('../controllers/crmController');
const inbox = require('../controllers/inboxController');
const audit = require('../controllers/auditController');
const analytics = require('../controllers/analyticsController');
const instagram = require('../controllers/instagramController');
const business = require('../controllers/businessController');
const settings = require('../controllers/settingsController');
const delivery = require('../controllers/deliveryController');
const inventory = require('../controllers/inventoryController');
const fraudProtection = require('../controllers/fraudProtectionController');
const customization = require('../controllers/websiteCustomizationController');
const notifications = require('../controllers/notificationController');
const productDraft = require('../controllers/productDraftController');
const variantGroup = require('../controllers/variantGroupController');
const reports = require('../controllers/reportController');
const storeContent = require('../controllers/storeContentController');
const { requireAnyStorePermission, requireStoreFeature, requireStorePermission, stripClientStoreId } = require('../middleware/storeMiddleware');

// Returning existing rentals must remain possible when new writes are paused.
router.use('/rentals', require('./rentalRoutes').staffRouter());
router.use('/settings/traffic', require('./trafficSettingsRoutes'));
router.use('/smart-fill', require('./workflowSmartFillRoutes'));

router.get('/products', requireStorePermission('catalog.read'), product.getProducts);
router.get('/products/smart-fill/status', requireStorePermission('catalog.read'), smartFill.status);
router.post('/products/smart-fill', requireStorePermission('catalog.write'), requireStoreFeature('aiProduct'), smartFill.limiter, smartFill.fill);
router.get('/products/quick-analyze/status', requireStorePermission('catalog.read'), product.getQuickAddVisionStatus);
router.post('/products/quick-analyze', requireStorePermission('catalog.write'), requireStoreFeature('aiProduct'), product.analyzeQuickAdd);
router.get('/products/export', requireStorePermission('catalog.read'), product.exportProducts);
router.get('/products/duplicate-check', requireStorePermission('catalog.read'), product.checkDuplicates);
router.post('/products/bulk', requireStorePermission('catalog.write'), requireBulkInventoryPermission, product.bulkUpdateProducts);
router.get('/products/:id', requireStorePermission('catalog.read'), product.getProductById);
router.post('/products', requireStorePermission('catalog.write'), stripClientStoreId, product.createProduct);
router.put('/products/:id', requireStorePermission('catalog.write'), stripClientStoreId, product.updateProduct);
router.delete('/products/:id', requireStorePermission('catalog.write'), product.deleteProduct);
router.get('/products/:id/deletion-preview', requireStorePermission('catalog.write'), product.productDeletionPreview);
router.delete('/products/:id/permanent', requireStorePermission('catalog.write'), product.permanentlyDeleteProduct);
router.post('/products/:id/duplicate', requireStorePermission('catalog.write'), product.duplicateProduct);
router.patch('/products/:id/restore', requireStorePermission('catalog.write'), product.restoreProduct);
router.patch('/products/:id/status', requireStorePermission('catalog.write'), product.updateStatus);
router.patch('/products/:id/stock', requireStorePermission('inventory.write'), product.updateStock);
router.patch('/products/:id/mark-out-of-stock', requireStorePermission('inventory.write'), product.markOutOfStock);
router.patch('/products/:id/hide', requireStorePermission('catalog.write'), product.hideProduct);
router.post('/product-drafts/bulk-upload', requireStorePermission('catalog.write'), productDraft.bulkUploadMiddleware.array('images', 30), productDraft.bulkUpload);
router.post('/product-drafts', requireStorePermission('catalog.write'), productDraft.createDraft);
router.get('/product-drafts', requireStorePermission('catalog.read'), productDraft.listDrafts);
router.get('/product-drafts/autosave', requireStorePermission('catalog.read'), productDraft.getAutosave);
router.put('/product-drafts/autosave', requireStorePermission('catalog.write'), productDraft.saveAutosave);
router.get('/product-drafts/:id', requireStorePermission('catalog.read'), productDraft.getDraft);
router.put('/product-drafts/:id', requireStorePermission('catalog.write'), productDraft.updateDraft);
router.patch('/product-drafts/:id/archive', requireStorePermission('catalog.write'), productDraft.archiveDraft);
router.patch('/product-drafts/:id/restore', requireStorePermission('catalog.write'), productDraft.restoreDraft);
router.delete('/product-drafts/:id', requireStorePermission('catalog.write'), productDraft.deleteDraft);
router.post('/product-drafts/publish-selected', requireStorePermission('catalog.write'), productDraft.publishSelected);
router.get('/variant-groups', requireStorePermission('catalog.read'), variantGroup.listGroups);
router.get('/variant-groups/candidates', requireStorePermission('catalog.read'), variantGroup.listCandidates);
router.get('/variant-groups/:id', requireStorePermission('catalog.read'), variantGroup.getGroup);
router.post('/variant-groups', requireStorePermission('catalog.write'), stripClientStoreId, variantGroup.createGroup);
router.put('/variant-groups/:id', requireStorePermission('catalog.write'), stripClientStoreId, variantGroup.updateGroup);
router.patch('/variant-groups/:id/archive', requireStorePermission('catalog.write'), variantGroup.archiveGroup);
router.patch('/variant-groups/:id/restore', requireStorePermission('catalog.write'), variantGroup.restoreGroup);
router.post('/variant-groups/:id/reconcile', requireStorePermission('catalog.write'), variantGroup.reconcileGroup);
router.post('/variant-groups/:id/add-products', requireStorePermission('catalog.write'), stripClientStoreId, variantGroup.addProducts);
router.post('/variant-groups/:id/remove-products', requireStorePermission('catalog.write'), stripClientStoreId, variantGroup.removeProducts);
router.delete('/variant-groups/:id', requireStorePermission('catalog.write'), variantGroup.deleteGroup);
router.get('/inventory/history', requireStorePermission('inventory.read'), inventory.history);
router.get('/inventory/catalog', requireStorePermission('inventory.read'), inventory.catalog);
router.get('/inventory/summary', requireStorePermission('inventory.read'), inventory.summary);
router.get('/inventory/export', requireStorePermission('inventory.export'), inventory.exportCatalog);
router.post('/inventory/adjustments', requireStorePermission('inventory.write'), inventory.adjust);
router.post('/inventory/adjustments/:id/reverse', requireStorePermission('inventory.approve'), inventory.reverse);
router.post('/inventory/bulk-adjustments', requireStorePermission('inventory.bulk'), inventory.bulkAdjust);
router.get('/inventory/purchase-orders', requireStorePermission('inventory.read'), inventory.listPurchaseOrders);
router.post('/inventory/purchase-orders', requireStorePermission('inventory.receive'), inventory.createPurchaseOrder);
router.post('/inventory/purchase-orders/:id/receive', requireStorePermission('inventory.receive'), inventory.receivePurchaseOrder);
router.post('/inventory/purchase-orders/:id/cancel', requireStorePermission('inventory.approve'), inventory.cancelPurchaseOrder);

router.get('/notifications', notifications.myNotifications);
router.get('/notifications/summary', notifications.summary);
router.patch('/notifications/read-all', notifications.markAllRead);
router.patch('/notifications/:id/read', notifications.markRead);

router.get('/orders', requireStorePermission('orders.read'), order.adminOrders);
router.get('/orders/workspace-summary', requireStorePermission('orders.read'), order.orderWorkspaceSummary);
router.get('/orders/:id', requireStorePermission('orders.read'), order.getOrder);
router.get('/orders/:id/receipt', requireStorePermission('orders.read'), order.receipt);
router.post('/orders/evidence/uploads', requireStorePermission('orders.write'), fraudProtection.evidenceUploadMiddleware, fraudProtection.uploadEvidence);
router.get('/orders/item-verification/:uniqueItemId', requireStorePermission('orders.read'), fraudProtection.verifyItemIdentity);
router.post('/orders/:id/item-identities/generate', requireStorePermission('orders.write'), fraudProtection.generateItemIdentities);
router.post('/orders/:id/packing/verify', requireStorePermission('orders.write'), fraudProtection.verifyPacking);
router.get('/orders/:id/verification-evidence', requireStorePermission('orders.read'), fraudProtection.getEvidence);
router.get('/orders/:id/delivery', requireStorePermission('orders.read'), delivery.details);
router.get('/orders/:id/delivery/label', requireStorePermission('orders.write'), requireStoreFeature('shippingAutomation'), delivery.label);
router.post('/orders/:id/delivery/:action', requireStorePermission('orders.write'), requireStoreFeature('shippingAutomation'), delivery.action);
router.put('/orders/:id/status', requireStorePermission('orders.write'), order.updateOrderStatus);
router.put('/orders/:id/payment-status', requireStorePermission('orders.write'), order.updatePaymentStatus);
router.post('/orders/:id/cancellation-refund', requireStorePermission('orders.write'), order.retryCancellationRefund);
router.post('/orders/:id/item-cancellation-refund', requireStorePermission('orders.write'), order.retryItemCancellationRefund);
router.post('/orders/:id/rto/inspect', requireStorePermission('orders.write'), order.inspectRto);
router.post('/orders/:id/rto/refund', requireStorePermission('orders.write'), order.retryRtoRefund);
router.patch('/orders/:id/staff-notes', requireStorePermission('orders.write'), order.addStaffNote);
router.put('/orders/:id/shipping-address', requireStorePermission('orders.write'), order.updateShippingAddress);
router.put('/orders/:id/shipment', requireStorePermission('orders.write'), order.updateShipment);
router.delete('/orders/:id', requireStorePermission('orders.write'), order.deleteOrder);

router.get('/coupons', requireStorePermission('marketing.read'), coupon.getCoupons);
router.get('/coupons/stats', requireStorePermission('marketing.read'), coupon.getCouponStats);
router.get('/coupons/code-availability', requireStorePermission('marketing.read'), coupon.checkCouponCode);
router.get('/coupons/options', requireStorePermission('marketing.read'), coupon.searchCouponOptions);
router.post('/coupons/bulk', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), coupon.bulkCouponAction);
router.get('/coupons/:id/insights', requireStorePermission('marketing.read'), coupon.getCouponInsights);
router.get('/coupons/:id/export', requireStorePermission('marketing.read'), coupon.exportCouponRedemptions);
router.post('/coupons/:id/simulate', requireStorePermission('marketing.read'), coupon.simulateCoupon);
router.post('/coupons', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), stripClientStoreId, coupon.createCoupon);
router.post('/coupons/:id/duplicate', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), stripClientStoreId, coupon.duplicateCoupon);
router.patch('/coupons/:id/status', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), coupon.updateCouponStatus);
router.patch('/coupons/:id/archive', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), coupon.archiveCoupon);
router.patch('/coupons/:id/restore', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), coupon.restoreCoupon);
router.put('/coupons/:id', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), stripClientStoreId, coupon.updateCoupon);
router.delete('/coupons/:id', requireStorePermission('marketing.write'), requireStoreFeature('coupons'), coupon.deleteCoupon);

router.get('/categories', requireStorePermission('catalog.read'), category.getCategories);
router.post('/categories', requireStorePermission('catalog.write'), stripClientStoreId, category.createCategory);
router.put('/categories/reorder', requireStorePermission('catalog.write'), stripClientStoreId, category.reorderCategories);
router.get('/categories/:id/impact', requireStorePermission('catalog.read'), category.getCategoryImpact);
router.post('/categories/:id/reassign', requireStorePermission('catalog.write'), stripClientStoreId, category.reassignCategory);
router.patch('/categories/:id/status', requireStorePermission('catalog.write'), stripClientStoreId, category.updateCategoryStatus);
router.patch('/categories/:id/archive', requireStorePermission('catalog.write'), category.archiveCategory);
router.patch('/categories/:id/restore', requireStorePermission('catalog.write'), category.restoreCategory);
router.get('/categories/:id', requireStorePermission('catalog.read'), category.getCategoryById);
router.put('/categories/:id', requireStorePermission('catalog.write'), stripClientStoreId, category.updateCategory);
router.delete('/categories/:id', requireStorePermission('catalog.write'), category.deleteCategory);

router.get('/banners', requireStorePermission('marketing.read'), banner.getBanners);
router.get('/banners/:id', requireStorePermission('marketing.read'), banner.getBannerById);
router.post('/banners', requireStorePermission('marketing.write'), stripClientStoreId, banner.createBanner);
router.put('/banners/reorder', requireStorePermission('marketing.write'), stripClientStoreId, banner.reorderBanners);
router.post('/banners/:id/duplicate', requireStorePermission('marketing.write'), stripClientStoreId, banner.duplicateBanner);
router.patch('/banners/:id/status', requireStorePermission('marketing.write'), stripClientStoreId, banner.updateBannerStatus);
router.patch('/banners/:id/restore', requireStorePermission('marketing.write'), stripClientStoreId, banner.restoreBanner);
router.put('/banners/:id', requireStorePermission('marketing.write'), stripClientStoreId, banner.updateBanner);
router.delete('/banners/:id', requireStorePermission('marketing.write'), banner.deleteBanner);

router.get('/campaigns', requireStorePermission('marketing.read'), requireStoreFeature('festival'), campaign.list);
router.post('/campaigns', requireStorePermission('marketing.write'), requireStoreFeature('festival'), stripClientStoreId, campaign.create);
router.get('/campaigns/:id', requireStorePermission('marketing.read'), requireStoreFeature('festival'), campaign.get);
router.put('/campaigns/:id', requireStorePermission('marketing.write'), requireStoreFeature('festival'), stripClientStoreId, campaign.update);
router.patch('/campaigns/:id/status', requireStorePermission('marketing.write'), requireStoreFeature('festival'), campaign.status);
router.post('/campaigns/:id/duplicate', requireStorePermission('marketing.write'), requireStoreFeature('festival'), stripClientStoreId, campaign.duplicate);
router.post('/campaigns/:id/repair', requireStorePermission('marketing.write'), requireStoreFeature('festival'), campaign.repair);

router.get('/reviews/management/stats', requireStorePermission('reviews.read'), review.adminReviewStats);
router.get('/reviews/management/options', requireStorePermission('reviews.read'), review.adminReviewOptions);
router.get('/reviews/management/export', requireStorePermission('reviews.export'), review.adminReviewExport);
router.post('/reviews/management/bulk', requireStorePermission('reviews.moderate'), review.bulkReviewAction);
router.post('/reviews/management/reminders', requireStorePermission('reviews.reply'), review.sendReviewRequests);
router.get('/reviews/management/:id', requireStorePermission('reviews.read'), review.adminReviewDetail);
router.patch('/reviews/management/:id/moderation', requireStorePermission('reviews.moderate'), review.moderateReview);
router.patch('/reviews/management/:id/archive', requireStorePermission('reviews.moderate'), review.archiveReview);
router.patch('/reviews/management/:id/restore', requireStorePermission('reviews.moderate'), review.restoreReview);
router.patch('/reviews/management/:id/featured', requireStorePermission('reviews.moderate'), review.setFeatured);
router.put('/reviews/management/:id/reply', requireStorePermission('reviews.reply'), review.replyToReview);
router.delete('/reviews/management/:id/reply', requireStorePermission('reviews.reply'), review.deleteReply);
router.delete('/reviews/management/:id', requireStorePermission('reviews.delete'), review.deleteReview);
router.get('/reviews', requireStorePermission('reviews.read'), review.adminReviews);
router.get('/returns', requireStorePermission('returns.read'), returns.adminReturns);
router.get('/returns/stats', requireStorePermission('returns.read'), returns.adminReturnStats);
router.get('/returns/:id', requireStorePermission('returns.read'), returns.getReturnDetail);
router.post('/returns/evidence/uploads', requireStorePermission('returns.write'), fraudProtection.evidenceUploadMiddleware, fraudProtection.uploadEvidence);
router.post('/returns/:id/inspect', requireStorePermission('returns.qc'), fraudProtection.inspectReturn);
router.post('/returns/:id/decision', requireStorePermission('returns.refund'), fraudProtection.decideReturn);
router.put('/returns/:id/status', requireStorePermission('returns.write'), returns.updateReturnStatus);
router.patch('/returns/:id/meta', requireStorePermission('returns.write'), returns.updateReturnMeta);
router.post('/returns/:id/refund/retry', requireStorePermission('returns.refund'), returns.retryReturnRefund);
router.post('/returns/:id/exchange-adjustment/prepare', requireAnyStorePermission('returns.refund', 'returns.fulfil'), returns.prepareExchangeAdjustment);
router.get('/returns/:id/refund-destination', requireStorePermission('returns.refund.pii'), returns.revealRefundDestination);
router.post('/returns/:id/refund/reconcile', requireStorePermission('returns.refund'), returns.reconcileReturnRefund);
router.get('/returns/:id/delivery', requireStorePermission('returns.read'), (req, _res, next) => { req.deliveryReturn = true; next(); }, delivery.details);
router.get('/returns/:id/delivery/label', requireStorePermission('returns.ship'), requireStoreFeature('shippingAutomation'), (req, _res, next) => { req.deliveryReturn = true; next(); }, delivery.label);
router.post('/returns/:id/delivery/:action', requireStorePermission('returns.ship'), requireStoreFeature('shippingAutomation'), (req, _res, next) => { req.deliveryReturn = true; next(); }, delivery.action);
router.get('/returns/:id/replacement-delivery', requireStorePermission('returns.read'), (req, _res, next) => { req.deliveryReplacement = true; next(); }, delivery.details);
router.get('/returns/:id/replacement-delivery/label', requireStorePermission('returns.ship'), requireStoreFeature('shippingAutomation'), (req, _res, next) => { req.deliveryReplacement = true; next(); }, delivery.label);
router.post('/returns/:id/replacement-delivery/:action', requireStorePermission('returns.ship'), requireStoreFeature('shippingAutomation'), (req, _res, next) => { req.deliveryReplacement = true; next(); }, delivery.action);

router.get('/dashboard/stats', requireStorePermission('orders.read'), dashboard.stats);
router.get('/reports/options', requireStorePermission('reports.read'), requireStoreFeature('analytics'), reports.options);
router.get('/reports/views', requireStorePermission('reports.read'), requireStoreFeature('analytics'), reports.listViews);
router.post('/reports/views', requireStorePermission('reports.manage'), requireStoreFeature('analytics'), reports.createView);
router.put('/reports/views/:id', requireStorePermission('reports.manage'), requireStoreFeature('analytics'), reports.updateView);
router.delete('/reports/views/:id', requireStorePermission('reports.manage'), requireStoreFeature('analytics'), reports.deleteView);
router.post('/reports/views/:id/run', requireStorePermission('reports.manage'), requireStoreFeature('analytics'), reports.runView);
router.post('/reports/export', requireStorePermission('reports.export'), requireStoreFeature('analytics'), reports.exportReport);
router.get('/reports/center/:section', requireStorePermission('reports.read'), requireStoreFeature('analytics'), reports.section);
router.get('/reports/sales', requireStorePermission('orders.read'), dashboard.salesReport);
router.get('/reports/products', requireStorePermission('catalog.read'), dashboard.productReport);

router.get('/contact', requireStorePermission('support.read'), contact.adminList);
router.get('/newsletter', requireStorePermission('marketing.read'), newsletter.adminList);

router.get('/crm/export', requireStorePermission('crm.read'), requireStoreFeature('crm'), crm.exportCustomers);
router.put('/crm/settings', requireStorePermission('settings.write'), requireStoreFeature('crm'), crm.updateRules);
router.post('/crm/bulk-tags', requireStorePermission('crm.write'), requireStoreFeature('crm'), crm.bulkTags);
router.post('/crm/:userId/privacy-requests', requireStorePermission('crm.write'), requireStoreFeature('crm'), crm.createPrivacyRequest);
router.patch('/crm/:userId/privacy-requests/:requestId', requireStorePermission('crm.write'), requireStoreFeature('crm'), crm.updatePrivacyRequest);
router.get('/crm/:userId', requireStorePermission('crm.read'), requireStoreFeature('crm'), crm.get);
router.put('/crm/:userId/restrictions', requireStorePermission('crm.write'), requireStoreFeature('crm'), crm.updateRestrictions);
router.put('/crm/:userId', requireStorePermission('crm.write'), requireStoreFeature('crm'), crm.update);
router.get('/crm', requireStorePermission('crm.read'), requireStoreFeature('crm'), crm.list);

router.get('/inbox', requireStorePermission('inbox.read'), inbox.list);
router.get('/inbox/:id', requireStorePermission('inbox.read'), inbox.get);
router.post('/inbox/:id/reply', requireStorePermission('inbox.write'), inbox.reply);
router.put('/inbox/:id/status', requireStorePermission('inbox.write'), inbox.updateStatus);

router.get('/audit-logs', requireStorePermission('audit.read'), audit.list);
router.get('/audit-logs/options', requireStorePermission('audit.read'), audit.options);
router.get('/audit-logs/:id', requireStorePermission('audit.read'), audit.get);
router.get('/analytics/funnel', requireStorePermission('marketing.read'), requireStoreFeature('analytics'), analytics.funnel);

router.get('/business/overview', requireStorePermission('orders.read'), business.overview);
router.get('/business/abandoned-carts', requireStorePermission('marketing.read'), business.abandonedCarts);
router.post('/business/abandoned-carts/:id/reminder', requireStorePermission('marketing.write'), business.remindAbandonedCart);
router.post('/business/assistant', requireStorePermission('orders.read'), business.assistant);
router.post('/business/customer-offers', requireStorePermission('marketing.write'), business.customerOffer);
router.put('/business/festival', requireStorePermission('marketing.write'), business.updateFestival);
router.get('/settings', requireStorePermission('settings.read'), settings.getSettings);
router.use('/settings/order-alerts', requireStorePermission('settings.write'), require('./orderAlertRoutes'));
router.put('/settings', requireStorePermission('settings.write'), stripClientStoreId, settings.updateSettings);
router.get('/settings/payment-readiness', requireStorePermission('settings.read'), settings.getPaymentReadiness);
router.get('/settings/shipping-readiness', requireStorePermission('settings.read'), delivery.readiness);
router.get('/design', requireStorePermission('design.read'), customization.getSellerDesign);
router.put('/design', requireStorePermission('design.write'), customization.updateSellerDesign);
router.post('/design/preflight', requireStorePermission('design.read'), customization.preflightSellerDesign);
router.post('/design/discard', requireStorePermission('design.write'), customization.discardSellerDesign);
router.get('/design/history', requireStorePermission('design.read'), customization.getSellerDesignHistory);
router.post('/design/history/:versionId/restore', requireStorePermission('design.write'), customization.restoreSellerDesignVersion);
router.post('/design/publish', requireStorePermission('design.publish'), customization.publishSellerDesign);
router.post('/design/schedule', requireStorePermission('design.publish'), customization.scheduleSellerDesign);
router.delete('/design/schedule', requireStorePermission('design.publish'), customization.cancelSellerDesignSchedule);
router.get('/content', requireStorePermission('content.read'), storeContent.get);
router.put('/content/draft', requireStorePermission('content.write'), storeContent.saveDraft);
router.post('/content/preflight', requireStorePermission('content.read'), storeContent.preflight);
router.post('/content/publish', requireStorePermission('content.publish'), storeContent.publish);
router.post('/content/schedule', requireStorePermission('content.publish'), storeContent.schedule);
router.delete('/content/schedule', requireStorePermission('content.publish'), storeContent.cancelSchedule);
router.post('/content/schedule/retry', requireStorePermission('content.publish'), storeContent.retrySchedule);
router.get('/content/history', requireStorePermission('content.read'), storeContent.history);
router.post('/content/history/:versionId/restore', requireStorePermission('content.write'), storeContent.restore);

router.use('/uploads', requireAnyStorePermission('catalog.write', 'design.write'), require('./uploadRoutes'));

router.get('/instagram', requireStorePermission('instagram.read'), requireStoreFeature('socialStudio'), instagram.status);
router.get('/instagram/connect-url', requireStorePermission('instagram.write'), requireStoreFeature('socialStudio'), instagram.connectUrl);
router.get('/instagram/media', requireStorePermission('instagram.read'), requireStoreFeature('socialStudio'), instagram.media);
router.post('/instagram', requireStorePermission('instagram.write'), requireStoreFeature('socialStudio'), instagram.saveStub);

router.get('/shipping/provider', requireStorePermission('orders.read'), delivery.readiness);

function requireBulkInventoryPermission(req, res, next) {
  if (String(req.body?.action || '') !== 'out-of-stock') return next();
  return requireStorePermission('inventory.write')(req, res, next);
}

module.exports = router;
