const router = require('express').Router();
router.use('/order-alerts', require('./orderAlertRoutes'));
router.use('/traffic', require('../middleware/authMiddleware').protect, require('../middleware/adminMiddleware').adminOnly, require('./trafficSettingsRoutes'));
const settings = require('../controllers/settingsController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const sms = require('../controllers/smsSettingsController');
const smsLimit = require('express-rate-limit')({ windowMs: 15 * 60000, max: 30, keyGenerator: req => String(req.user._id), standardHeaders: true, legacyHeaders: false });
router.get('/sms', protect, adminOnly, sms.authorize, sms.read);
router.put('/sms', protect, adminOnly, sms.authorize, smsLimit, sms.save);
router.post('/sms/test', protect, adminOnly, sms.authorize, smsLimit, sms.test);
router.post('/sms/activate', protect, adminOnly, sms.authorize, smsLimit, sms.activate);
router.post('/sms/discard', protect, adminOnly, sms.authorize, smsLimit, sms.discard);
router.get('/', settings.getSettings);
router.get('/payment-methods', settings.getPaymentMethods);
router.get('/payment-readiness', protect, adminOnly, settings.getPaymentReadiness);
router.get('/shipping-readiness', protect, adminOnly, require('../controllers/deliveryController').readiness);
router.put('/', protect, adminOnly, settings.updateSettings);
router.put('/admin/update', protect, adminOnly, settings.updateSettings);
module.exports = router;
