const fs = require('node:fs/promises');
const sharp = require('sharp');
const { ApiError } = require('../utils/apiError');

const PHOTO_SOURCE_MAX_BYTES = 20 * 1024 * 1024;
const PHOTO_BATCH_MAX_BYTES = 60 * 1024 * 1024;
const PHOTO_PRIVATE_MAX_BYTES = 8 * 1024 * 1024;
const prepared = new WeakMap();
const photoTypes = new Set(['image/jpeg', 'image/jpg', 'image/png', 'image/webp']);
const invalid = message => new ApiError('UPLOAD_IMAGE_INVALID', message, { statusCode: 400 });
let work = Promise.resolve();

// Decode/optimize one photo at a time across requests, including disk-staged
// uploads. Large batches must not decode several 50-megapixel photos together.
function photoWork(task) {
  const pending = work.then(task);
  work = pending.catch(() => {});
  return pending;
}

async function decodedImage(source) {
  if (!Buffer.isBuffer(source) || !source.length || source.length > PHOTO_SOURCE_MAX_BYTES) throw invalid('Choose a photo up to 20 MB.');
  const image = sharp(source, { limitInputPixels: 50000000, failOn: 'warning' });
  const metadata = await image.metadata();
  if (!['jpeg', 'png', 'webp'].includes(metadata.format) || (metadata.pages || 1) !== 1) throw invalid('Use a single JPG, PNG or WebP photo, not SVG or animation.');
  // A valid header alone does not prove the encoded image is usable.
  await image.clone().stats();
  return { image, metadata };
}

async function optimizePhoto(source) {
  try {
    const { image, metadata } = await decodedImage(source);
    let buffer = require('../utils/imageMetadata')[metadata.format](source);
    // Apply orientation without another lossy generation. High bit-depth PNGs
    // keep their original depth; rotation is encoded as lossless PNG.
    if (metadata.orientation && metadata.orientation !== 1) {
      let oriented = image.clone().rotate().keepIccProfile();
      if (metadata.depth === 'ushort') oriented = oriented.toColourspace('rgb16').png({ compressionLevel: 9 });
      else oriented = oriented.png({ compressionLevel: 6 });
      buffer = await oriented.toBuffer();
    } else if (metadata.format === 'png' && metadata.depth === 'uchar' && metadata.space === 'srgb' && !metadata.icc) {
      const optimized = await sharp(buffer, { limitInputPixels: 50000000 }).png({ compressionLevel: 6, adaptiveFiltering: true, palette: false }).toBuffer();
      if (optimized.length < buffer.length) buffer = optimized;
    }
    const output = await sharp(buffer).metadata();
    return { buffer, mimeType: `image/${output.format}`, width: output.width, height: output.height,
      skipped: buffer === source, lossless: true };
  } catch (error) {
    if (error instanceof ApiError) throw error;
    throw invalid('This photo could not be decoded. Choose a valid JPG, PNG or WebP photo.');
  }
}

function compressPhotoBuffer(source) { return photoWork(() => optimizePhoto(source)); }

// The URL saved as `url` remains the native master. These display derivatives
// resize from that master, retain alpha and use lossless WebP encoding.
function responsivePhotoVariants(file) {
  return photoWork(async () => {
    const source = file.buffer || await fs.readFile(file.path);
    // Prepared masters already passed a full decode. Avoid repeating stats for
    // every display copy; all output buffers below are generated by Sharp.
    const image = sharp(source, { limitInputPixels: 50000000, failOn: 'warning' });
    const metadata = prepared.has(file) ? await image.metadata() : (await decodedImage(source)).metadata;
    const nativeWidth = metadata.autoOrient?.width || ([5, 6, 7, 8].includes(metadata.orientation) ? metadata.height : metadata.width);
    const widths = [...new Set([320, 640, 1200, 2000].map(width => Math.min(width, nativeWidth)))];
    const rows = [];
    for (const width of widths) {
      const { data, info } = await image.clone().rotate().resize({ width, withoutEnlargement: true }).webp({ lossless: true, effort: 1 }).toBuffer({ resolveWithObject: true });
      const row = { buffer: data, mimetype: 'image/webp', size: data.length, originalname: `display-${info.width}.webp`, width: info.width, height: info.height,
        photo: { width: info.width, height: info.height, lossless: true, skipped: true } };
      prepared.set(row, Promise.resolve(row));
      rows.push(row);
    }
    return rows;
  });
}

// AI gets a bounded analysis derivative; storage always uses optimizePhoto.
function prepareAnalysisPhotoBuffer(source, { maxBytes = 1024 * 1024, maxEdge = 1600 } = {}) {
  return photoWork(async () => {
    try {
      const { image, metadata } = await decodedImage(source);
      if (source.length <= maxBytes && Math.max(metadata.width, metadata.height) <= maxEdge && !metadata.exif && !metadata.xmp && !metadata.iptc && !metadata.orientation) {
        return { buffer: source, mimeType: `image/${metadata.format}` };
      }
      let edge = maxEdge;
      for (let attempt = 0; attempt < 6; attempt++) {
        const buffer = await image.clone().rotate().resize({ width: edge, height: edge, fit: 'inside', withoutEnlargement: true })
          .webp({ quality: 95, alphaQuality: 100, effort: 4 }).toBuffer();
        if (buffer.length <= maxBytes) return { buffer, mimeType: 'image/webp' };
        edge = Math.floor(edge * 0.8);
      }
      throw invalid('This photo is too detailed for AI analysis. Try a closer view.');
    } catch (error) {
      if (error instanceof ApiError) throw error;
      throw invalid('This photo could not be decoded for AI analysis.');
    }
  });
}

async function preparePhotoFile(file) {
  if (!photoTypes.has(String(file?.mimetype || '').toLowerCase())) {
    if (String(file?.mimetype || '').startsWith('image/')) throw invalid('Only JPG, PNG and WebP photos are allowed.');
    return file;
  }
  if (prepared.has(file)) return prepared.get(file);
  const pending = photoWork(async () => {
    if (Number(file.size) > PHOTO_SOURCE_MAX_BYTES) throw invalid('Choose a photo up to 20 MB.');
    const source = file.buffer || await fs.readFile(file.path);
    const photo = await optimizePhoto(source);
    const result = { ...file, ...(photo.skipped && !file.buffer ? {} : { buffer: photo.buffer }),
      mimetype: photo.mimeType, size: photo.buffer.length,
      photo: { width: photo.width, height: photo.height, skipped: photo.skipped, lossless: true } };
    prepared.set(result, Promise.resolve(result));
    return result;
  });
  prepared.set(file, pending);
  try { return await pending; } catch (error) { prepared.delete(file); throw error; }
}

module.exports = { PHOTO_SOURCE_MAX_BYTES, PHOTO_BATCH_MAX_BYTES, PHOTO_PRIVATE_MAX_BYTES,
  compressPhotoBuffer, prepareAnalysisPhotoBuffer, preparePhotoFile, responsivePhotoVariants };
