const M = require('../models/Rental');
const Store = require('../models/Store');
const I = require('./rentalInventoryRules');

// Only the untouched, single-product drafts generated by the product editor
// have this shape. A Studio save/pause increments revision and marks its origin.
// Custom bundles, prices, pieces and intentionally paused offers are untouched.
function isLegacyProductOffer(row) {
  const r = row.requirements?.[0];
  return !row.publicationOrigin && row.active === false && row.revision === 0 &&
    r && I.usesProductInventory(r, row) && r.quantity === 1 &&
    !row.variantId && !row.size && !row.colour && !r.variantId && !r.size && !r.colour &&
    !row.notes && !row.packages?.length && !row.cleaningFeePaise && !row.alterationFeePaise &&
    Number.isSafeInteger(row.dailyRatePaise) && row.dailyRatePaise > 0 &&
    Number.isSafeInteger(row.depositPaise) && row.depositPaise >= 0;
}

async function repairLegacyProductOffers() {
  const S = require('./rentalService');
  let after, updated = 0, scanned = 0;
  while (true) {
    const rows = await M.Listing.find({ active: false, revision: 0, matchingVersion: 2,
      publicationOrigin: { $exists: false }, ...(after ? { _id: { $gt: after } } : {}) })
      .sort('_id').limit(100).lean();
    if (!rows.length) break;
    scanned += rows.length; after = rows[rows.length - 1]._id;
    const grouped = new Map();
    for (const row of rows.filter(isLegacyProductOffer)) {
      const id = String(row.storeId);
      if (!grouped.has(id)) grouped.set(id, []);
      grouped.get(id).push(row._id);
    }
    for (const [id, ids] of grouped) {
      const store = await Store.findById(id);
      if (!store) continue;
      const count = await S.transaction(store, async session => {
        const result = await M.Listing.updateMany({ storeId: store._id, _id: { $in: ids },
          active: false, revision: 0, publicationOrigin: { $exists: false } },
        { $set: { active: true, publicationOrigin: 'PRODUCT' }, $inc: { revision: 1 } }, { session });
        return result.modifiedCount;
      });
      updated += count;
    }
  }
  return { scanned, updated };
}

module.exports = { isLegacyProductOffer, repairLegacyProductOffers };
