const mongoose = require('mongoose');
const storeIdPlugin = require('./plugins/storeId');

const imageSchema = new mongoose.Schema({
  url: String,
  publicId: String,
  background: { type: require('./imageBackgroundSchema'), default: undefined },
  primary: { type: Boolean, default: false },
  sourceFrame: { type: new mongoose.Schema({ timestampSeconds: Number, qualityScore: Number, viewType: String, width: Number, height: Number, selectionVersion: String }, { _id: false }), default: undefined },
}, { _id: false });

const videoSchema = new mongoose.Schema({
  url: String,
  publicId: String,
  thumbnail: String,
}, { _id: false });

const sizeChartRowSchema = new mongoose.Schema({
  size: String,
  acrossShoulder: Number,
  sleeveLength: Number,
  bust: Number,
  chest: Number,
  waist: Number,
  frontLength: Number,
  bottomLength: Number,
  hips: Number,
  outseamLength: Number,
  inseamLength: Number,
}, { _id: false });

const productDraftSchema = new mongoose.Schema({
  name: String,
  slug: String,
  sku: String,
  image: String,
  images: [imageSchema],
  videos: [videoSchema],
  category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
  subCategory: String,
  price: Number,
  originalPrice: Number,
  sellingPrice: Number,
  costPrice: Number,
  gstRate: Number,
  hsnCode: String,
  barcode: String,
  commerceMode: { type: String, enum: ['SALE_ONLY', 'RENTAL_ONLY', 'SALE_AND_RENTAL'], default: 'SALE_ONLY' },
  rentalPricing: { type: mongoose.Schema.Types.Mixed, default: undefined },
  stock: Number,
  lowStockAlert: Number,
  reorderQuantity: Number,
  shippingWeightKg: Number,
  packageDimensions: {
    lengthCm: Number,
    widthCm: Number,
    heightCm: Number,
  },
  countryOfOrigin: String,
  manufacturerDetails: String,
  warranty: String,
  supplierName: String,
  supplierSku: String,
  restockAt: Date,
  publishAt: Date,
  salePrice: Number,
  saleStartAt: Date,
  saleEndAt: Date,
  sizes: [String],
  sizingMode: { type: String, enum: ['auto', 'sized', 'free-size'], default: 'auto' },
  sizeChartProfile: { type: String, default: 'auto' },
  sizeChart: {
    unit: { type: String, enum: ['in', 'cm'], default: 'in' },
    columns: { type: [String], default: [] },
    rows: { type: [sizeChartRowSchema], default: [] },
  },
  sizeFitNotes: String,
  colors: [String],
  fabric: String,
  occasion: String,
  completeLookProductIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
  tags: [String],
  attributeValues: { type: Map, of: String, default: {} },
  description: String,
  shortDescription: String,
  highlights: [String],
  careInstructions: String,
  returnPolicy: String,
  returnable: { type: Boolean, default: true },
  exchangeable: { type: Boolean, default: true },
  returnWindowDays: { type: Number, min: 0, max: 365 },
  metaTitle: String,
  metaDescription: String,
  metaKeywords: String,
  isFeatured: Boolean,
  isNewArrival: Boolean,
  isBestSeller: Boolean,
  showOnHomepage: Boolean,
  showInTrending: Boolean,
  showInFestive: Boolean,
  variants: { type: [mongoose.Schema.Types.Mixed], default: [] },
  status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft', index: true },
  revision: { type: Number, default: 0, min: 0 },
  archivedAt: { type: Date, default: null },
  lastSavedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: undefined },
  lastPublishAttemptAt: { type: Date, default: null },
  lastPublishError: { type: String, maxlength: 500, default: '' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  publishedProductId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
  publishingToken: { type: String, select: false },
  uploadOperationId: { type: String, select: false },
  sourceType: { type: String, enum: ['manual', 'reel-import', 'social-import'], default: undefined },
  autosaveKey: { type: String, trim: true, maxlength: 80, default: undefined },
  sourceSocialImportId: { type: mongoose.Schema.Types.ObjectId, ref: 'SocialProductImport', unique: true, sparse: true, default: undefined },
  sourceUrl: String,
  sourcePlatform: String,
  importContext: { type: mongoose.Schema.Types.Mixed, default: undefined },
  sourceJobId: { type: mongoose.Schema.Types.ObjectId, ref: 'ReelImport', default: undefined },
  sourceCandidateId: { type: mongoose.Schema.Types.ObjectId, ref: 'ReelCandidate', unique: true, sparse: true, default: undefined },
  confidence: { type: Number, min: 0, max: 1 },
  detectedColors: [String],
  detectedPattern: String,
  suggestedCategory: String,
  suggestedTags: [String],
  draftTitle: String,
  draftDescription: String,
}, { timestamps: true });

productDraftSchema.plugin(storeIdPlugin);
productDraftSchema.index({ storeId: 1, createdBy: 1, autosaveKey: 1 }, { unique: true, partialFilterExpression: { autosaveKey: { $type: 'string' } } });
productDraftSchema.index({ storeId: 1, status: 1, updatedAt: -1 });
productDraftSchema.index({ storeId: 1, sourceType: 1, updatedAt: -1 });
productDraftSchema.index({ storeId: 1, category: 1, updatedAt: -1 });

module.exports = mongoose.model('ProductDraft', productDraftSchema);
