const mongoose = require('mongoose');
const storeIdPlugin = require('./plugins/storeId');

const RETURN_STATUSES = [
  'Requested',
  'Approved',
  'Rejected',
  'Cancelled',
  'Pickup Scheduled',
  'Picked Up',
  'In Transit',
  'Received',
  'Inspection Pending',
  'Verified',
  'Mismatch Found',
  'QC Passed',
  'QC Failed',
  'Refund Initiated',
  'Exchange Allocated',
  'Replacement Shipped',
  'Replacement Delivered',
  'Exchanged',
  'Refunded',
  'Closed',
];

const REFUND_METHODS = ['ORIGINAL_PAYMENT', 'UPI', 'BANK_TRANSFER', 'STORE_CREDIT', 'MANUAL'];
const INVENTORY_DISPOSITIONS = ['PENDING', 'RESTOCK', 'QUARANTINE', 'DAMAGED', 'MISSING', 'DISPOSE'];

const returnExchangeSchema = new mongoose.Schema({
  caseNumber: { type: String, trim: true, maxlength: 40 },
  order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', required: true },
  product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  orderItemId: String,
  variantId: String,
  size: String,
  color: String,
  sku: String,
  quantity: { type: Number, default: 1, min: 1 },
  type: { type: String, enum: ['return', 'exchange'], required: true },
  reason: String,
  comment: String,
  photos: [String],
  customerEvidence: [{
    type: { type: String, enum: ['CUSTOMER_PHOTO', 'CUSTOMER_VIDEO'] },
    fileUrl: String,
    mimeType: String,
    sizeBytes: Number,
  }],
  pickupAddress: Object,
  productSnapshot: {
    name: String,
    image: String,
    unitPrice: Number,
    unitMrp: Number,
    tax: Number,
    returnPolicy: String,
  },
  policySnapshot: {
    windowDays: Number,
    deadline: Date,
    returnable: { type: Boolean, default: true },
    exchangeable: { type: Boolean, default: true },
    terms: String,
  },
  exchangeVariantId: String,
  exchangeSize: String,
  exchangeColor: String,
  adminComment: String,
  status: { type: String, enum: RETURN_STATUSES, default: 'Requested' },
  active: { type: Boolean, default: true },
  resolutionStatus: { type: String, enum: ['Refunded', 'Exchanged'] },
  refundMethod: { type: String, enum: REFUND_METHODS, default: 'ORIGINAL_PAYMENT' },
  refundDestinationSummary: {
    label: String,
    accountLast4: String,
  },
  refundDestinationEncrypted: { type: String, select: false },
  financial: {
    currency: { type: String, default: 'INR' },
    merchandiseAmount: { type: Number, default: 0 },
    allocatedCouponDiscount: { type: Number, default: 0 },
    allocatedPrepaidDiscount: { type: Number, default: 0 },
    estimatedRefundAmount: { type: Number, default: 0 },
    refundableDeliveryCharge: { type: Number, default: 0 },
    refundablePlatformFee: { type: Number, default: 0 },
    refundableCodCharge: { type: Number, default: 0 },
    returnShippingCharge: { type: Number, default: 0 },
    restockingFee: { type: Number, default: 0 },
    approvedRefundAmount: { type: Number, default: 0 },
    refundedAmount: { type: Number, default: 0 },
    refundStatus: { type: String, enum: ['NOT_REQUIRED', 'PENDING', 'INITIATED', 'PROCESSED', 'FAILED'], default: 'PENDING' },
    refundReference: String,
    initiatedAt: Date,
    expectedBy: Date,
    processedAt: Date,
    refundAttemptCount: { type: Number, default: 0, min: 0 },
    lastRefundAttemptAt: Date,
    lastRefundError: String,
    nextRefundCheckAt: Date,
    exchangeUnitPrice: { type: Number, default: 0 },
    exchangePriceDifference: { type: Number, default: 0 },
    exchangeAdjustmentStatus: { type: String, enum: ['NOT_REQUIRED', 'AMOUNT_DUE', 'PAYMENT_LINK_CREATED', 'CREDIT_DUE', 'CREDIT_PROCESSING', 'FAILED', 'SETTLED'], default: 'NOT_REQUIRED' },
    exchangeAdjustmentReference: String,
    exchangeAdjustmentSettledAt: Date,
    exchangePaymentLinkId: String,
    exchangePaymentLinkUrl: String,
    exchangePaymentLinkExpiresAt: Date,
    exchangePaymentId: String,
    exchangeAdjustmentLastError: String,
  },
  qc: {
    status: { type: String, enum: ['PENDING', 'PASSED', 'FAILED', 'NOT_REQUIRED'], default: 'PENDING' },
    receivedQuantity: { type: Number, min: 0 },
    disposition: { type: String, enum: INVENTORY_DISPOSITIONS, default: 'PENDING' },
    notes: String,
    inspectedAt: Date,
    inspectedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  inspection: {
    status: { type: String, enum: ['NOT_STARTED', 'PENDING', 'VERIFIED', 'MISMATCH_FOUND', 'MANUAL_REVIEW'], default: 'NOT_STARTED' },
    expectedUniqueItemIds: { type: [String], default: [] },
    returnedUniqueItemIds: { type: [String], default: [] },
    dispatchWeightGrams: Number,
    returnWeightGrams: Number,
    weightDifferenceGrams: Number,
    sealCondition: { type: String, enum: ['NOT_CHECKED', 'INTACT', 'BROKEN', 'MISSING', 'MISMATCH'], default: 'NOT_CHECKED' },
    returnedSealId: String,
    tagCondition: { type: String, enum: ['NOT_CHECKED', 'PRESENT', 'REMOVED', 'MISSING', 'MISMATCH'], default: 'NOT_CHECKED' },
    returnedTagId: String,
    condition: { type: String, enum: ['UNOPENED', 'GOOD', 'USED', 'DAMAGED', 'DIFFERENT_ITEM', 'MISSING_ITEM'] },
    flags: { type: [String], default: [] },
    result: { type: String, enum: ['NOT_CHECKED', 'VERIFIED', 'POSSIBLE_PRODUCT_SWAP', 'SECURITY_TAG_ISSUE', 'WEIGHT_DIFFERENCE', 'MANUAL_REVIEW_REQUIRED'], default: 'NOT_CHECKED' },
    notes: String,
    evidenceCount: { type: Number, default: 0, min: 0 },
    inspectedAt: Date,
    inspectedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  refundDecision: {
    decision: { type: String, enum: ['PENDING', 'APPROVED', 'PARTIAL', 'REJECTED', 'MORE_INFORMATION_REQUIRED'], default: 'PENDING' },
    reason: String,
    customerMessage: String,
    decidedAt: Date,
    decidedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  statusTimeline: [{
    status: String,
    note: String,
    source: { type: String, enum: ['CUSTOMER', 'ADMIN', 'SELLER', 'COURIER', 'SYSTEM'], default: 'SYSTEM' },
    actor: { id: String, name: String },
    date: { type: Date, default: Date.now },
  }],
  priority: { type: String, enum: ['LOW', 'NORMAL', 'HIGH', 'URGENT'], default: 'NORMAL' },
  assignee: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  tags: { type: [String], default: [] },
  internalNotes: [{
    text: { type: String, maxlength: 1000 },
    author: { id: String, name: String },
    date: { type: Date, default: Date.now },
  }],
  revision: { type: Number, default: 0 },
  operation: { type: String, default: '', select: false },
  operationUntil: { type: Date, select: false },
  inventoryRestored: { type: Boolean, default: false },
  inventoryRestoredAt: Date,
  inventoryDispositionRecorded: { type: Boolean, default: false },
  inventoryDispositionRecordedAt: Date,
  exchangeDeducted: { type: Boolean, default: false },
  exchangeReservedAt: Date,
  exchangeReservationExpiresAt: Date,
  exchangeReservationReleased: { type: Boolean, default: false },
  pickupScheduledAt: Date,
  pickedUpAt: Date,
  receivedAt: Date,
  cancelledAt: Date,
  completedAt: Date,
  slaDueAt: Date,
  shipment: { type: mongoose.Schema.Types.ObjectId, ref: 'ReverseShipment' },
  replacementShipment: { type: mongoose.Schema.Types.ObjectId, ref: 'ReplacementShipment' },
  replacementManualReference: { type: String, trim: true, maxlength: 120 },
}, { timestamps: true });

returnExchangeSchema.plugin(storeIdPlugin);
returnExchangeSchema.index({ order: 1, product: 1, createdAt: -1 });
returnExchangeSchema.index({ user: 1, createdAt: -1 });
returnExchangeSchema.index({ storeId: 1, status: 1, createdAt: -1 });
returnExchangeSchema.index({ storeId: 1, 'qc.status': 1, 'financial.refundStatus': 1, updatedAt: -1 });
returnExchangeSchema.index({ storeId: 1, slaDueAt: 1, status: 1 });
returnExchangeSchema.index({ storeId: 1, priority: 1, assignee: 1, updatedAt: -1 });
returnExchangeSchema.index({ storeId: 1, 'financial.nextRefundCheckAt': 1, 'financial.refundStatus': 1 });
returnExchangeSchema.index(
  { storeId: 1, caseNumber: 1 },
  { unique: true, partialFilterExpression: { caseNumber: { $type: 'string' } } },
);
returnExchangeSchema.index({ storeId: 1, order: 1, orderItemId: 1, active: 1 }, { unique: true, partialFilterExpression: { active: true }, name: 'one_active_return_per_order_item' });

module.exports = mongoose.model('ReturnExchange', returnExchangeSchema);
module.exports.RETURN_STATUSES = RETURN_STATUSES;
module.exports.REFUND_METHODS = REFUND_METHODS;
module.exports.INVENTORY_DISPOSITIONS = INVENTORY_DISPOSITIONS;
