const mongoose = require('mongoose');

const settingsSchema = new mongoose.Schema({
  storeName: { type: String, default: 'Jassi General Store' },
  brandIdentityEnabled: { type: Boolean, default: false },
  contactDetailsEnabled: { type: Boolean, default: false },
  logoUrl: String,
  faviconUrl: String,
  tagline: String,
  seoTitle: String,
  seoDescription: String,
  socialShareImage: String,
  searchIndexingEnabled: { type: Boolean, default: true },
  occasionShoppingEnabled: { type: Boolean, default: true },
  recentlyViewedEnabled: { type: Boolean, default: true },
  completeLookEnabled: { type: Boolean, default: true },
  announcementEnabled: Boolean,
  announcementText: String,
  supportHours: String,
  invoiceNote: String,
  acceptingOrders: { type: Boolean, default: true },
  orderPauseMessage: { type: String, default: 'We are temporarily not accepting new orders. Please check back soon.' },
  minimumOrderAmount: { type: Number, default: 0, min: 0 },
  contactEmail: String,
  contactPhone: String,
  whatsappNumber: String,
  address: String,
  shippingProvider: { type: String, enum: ['manual', 'bluedart', 'shiprocket', 'delhivery', 'xpressbees'], default: 'manual' },
  manualDeliveryMode: { type: String, enum: ['COURIER', 'SELF'], default: 'COURIER' },
  shippingPricingMode: { type: String, enum: ['fixed', 'weight', 'carrier'], default: 'fixed' },
  shippingFreeAboveEnabled: { type: Boolean, default: true },
  shippingDefaultWeightKg: { type: Number, default: 0.5, min: 0.001 },
  shippingLengthCm: { type: Number, default: 30, min: 0.1 },
  shippingWidthCm: { type: Number, default: 25, min: 0.1 },
  shippingHeightCm: { type: Number, default: 5, min: 0.1 },
  shippingVolumetricDivisor: { type: Number, default: 5000, min: 1 },
  shippingWeightStepKg: { type: Number, default: 0.5, min: 0.001 },
  shippingAdditionalStepCharge: { type: Number, default: 0, min: 0 },
  shippingRateZones: { type: [{ _id: false, prefix: String, baseCharge: Number, additionalStepCharge: Number }], default: [] },
  shippingPickup: { type: new mongoose.Schema({ fullName: String, mobile: String, houseNo: String, area: String, city: String, state: String, pincode: String }, { _id: false }), default: () => ({}) },
  freeShippingMinAmount: { type: Number, default: 999 },
  deliveryCharge: { type: Number, default: 99 },
  codEnabled: { type: Boolean, default: true },
  codCharge: { type: Number, default: 0 },
  codMaxAmount: Number,
  razorpayEnabled: { type: Boolean, default: false },
  upiEnabled: { type: Boolean, default: true },
  cardPaymentEnabled: { type: Boolean, default: true },
  netBankingEnabled: { type: Boolean, default: true },
  walletEnabled: { type: Boolean, default: true },
  socialLinks: Object,
  footerText: String,
  returnPolicy: String,
  privacyPolicy: String,
  termsConditions: String,
  shippingPolicy: String,
  cancellationPolicy: String,
  sizeGuide: String,
  faqs: String,
  ourStory: String,
  legalBusinessName: String,
  gstin: String,
  gstRate: { type: Number, default: 5 },
  platformFee: { type: Number, default: 23 },
  invoicePrefix: { type: String, default: 'SC' },
  billingAddress: String,
  returnWindowDays: { type: Number, default: 7 },
  returnsEnabled: { type: Boolean, default: true },
  refundDeliveryChargeOnFullReturn: { type: Boolean, default: false },
  refundPlatformFeeOnFullReturn: { type: Boolean, default: false },
  refundCodChargeOnFullReturn: { type: Boolean, default: false },
  customerReturnShippingCharge: { type: Number, default: 0, min: 0 },
  customerRestockingFeePercent: { type: Number, default: 0, min: 0, max: 100 },
  exchangeReservationHours: { type: Number, default: 168, min: 1, max: 720 },
  returnSlaHours: { type: Number, default: 24, min: 1, max: 720 },
  requireProductQrScan: { type: Boolean, default: false },
  requirePackingPhotos: { type: Boolean, default: false },
  requirePackingVideo: { type: Boolean, default: false },
  requireDispatchWeight: { type: Boolean, default: false },
  requireSecuritySeal: { type: Boolean, default: false },
  requireReturnPhotos: { type: Boolean, default: false },
  requireReturnVideo: { type: Boolean, default: false },
  enableSecurityTag: { type: Boolean, default: false },
  enableCustomerRiskDetection: { type: Boolean, default: true },
  autoApproveVerifiedReturns: { type: Boolean, default: false },
  returnWeightToleranceGrams: { type: Number, default: 100, min: 0, max: 10000 },
  highValueVerificationThreshold: { type: Number, default: 5000, min: 0 },
  appLinks: Object,
  storeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Store', index: true },
  codMinAmount: { type: Number, default: 0 },
  codPincodes: { type: [String], default: [] },
  prepaidDiscountType: { type: String, enum: ['Percentage', 'Flat', ''], default: '' },
  prepaidDiscountValue: { type: Number, default: 0 },
  codConfirmationRequired: { type: Boolean, default: false },
  smartCodVerificationEnabled: { type: Boolean, default: true },
  codRtoRestrictionLimit: { type: Number, default: 2, min: 0, max: 100 },
  rtoBlockEnabled: { type: Boolean, default: false },
  rtoBlockMinOrders: { type: Number, default: 0 },
  rtoBlockThreshold: { type: Number, default: 0 },
  rtoRefundDeduction: { type: Number, default: 0, min: 0 },
}, { timestamps: true });

module.exports = mongoose.model('Settings', settingsSchema);
