const mongoose = require('mongoose');
const { BILLING_CYCLES, LICENSE_STATUSES, PLAN_IDS } = require('../config/storePlans');

const STORE_STATUSES = ['DRAFT', 'ONBOARDING', 'PUBLISHED', 'SUSPENDED'];

const addressShape = {
  fullName: String,
  mobile: String,
  pincode: String,
  state: String,
  city: String,
  houseNo: String,
  area: String,
  landmark: String,
};

const storeSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true, maxlength: 80 },
  slug: { type: String, required: true, unique: true, lowercase: true, trim: true, maxlength: 80 },
  legalName: { type: String, trim: true, maxlength: 120 },
  logo: String,
  coverImage: String,
  bio: { type: String, maxlength: 1000 },
  instagramHandle: { type: String, trim: true, maxlength: 80 },
  instagramUrl: { type: String, trim: true, maxlength: 300 },
  whatsappNumber: { type: String, trim: true, maxlength: 20 },
  supportEmail: { type: String, trim: true, maxlength: 120 },
  supportPhone: { type: String, trim: true, maxlength: 20 },
  currency: { type: String, default: 'INR', maxlength: 8 },
  timezone: { type: String, default: 'Asia/Kolkata', maxlength: 60 },
  pickupAddress: addressShape,
  returnAddress: addressShape,
  paymentReady: { type: Boolean, default: false },
  shippingReady: { type: Boolean, default: false },
  checkoutEnabled: { type: Boolean, default: true },
  salesEnabled: { type: Boolean, default: true },
  status: { type: String, enum: STORE_STATUSES, default: 'ONBOARDING', index: true },
  statusReason: { type: String, trim: true, maxlength: 500, default: '' },
  archivedAt: { type: Date, default: null },
  archivedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  isDefault: { type: Boolean, default: false, index: true },
  publishedAt: Date,
  portfolioRevision: { type: Number, default: 0, min: 0 },
  commerceUsageFence: { type: Number, default: 0, select: false },
  owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
  customDomain: { type: String, trim: true, lowercase: true, maxlength: 120 },
  industry: { type: String, default: 'fashion', trim: true, lowercase: true, maxlength: 40, index: true },
  catalogStructure: { type: mongoose.Schema.Types.Mixed },
  industryConfigurations: { type: mongoose.Schema.Types.Mixed, default: {} },
  industryMigration: {
    status: { type: String, enum: ['READY', 'IN_PROGRESS', 'REVIEW_REQUIRED', 'COMPLETED', 'FAILED', 'ROLLED_BACK'], default: 'READY' },
    fromIndustry: String,
    toIndustry: String,
    totalProducts: { type: Number, default: 0 },
    affectedProducts: { type: Number, default: 0 },
    missingRequired: { type: Number, default: 0 },
    invalidValues: { type: Number, default: 0 },
    incompatibleVariants: { type: Number, default: 0 },
    legacyAttributes: { type: Number, default: 0 },
    draftProducts: { type: Number, default: 0 },
    activeCarts: { type: Number, default: 0 },
    activeOrders: { type: Number, default: 0 },
    reviewAssignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    reviewNote: { type: String, trim: true, maxlength: 500, default: '' },
    failureMessage: { type: String, trim: true, maxlength: 500, default: '' },
    rollbackSnapshot: mongoose.Schema.Types.Mixed,
    createdCategoryIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Category' }],
    checkedAt: Date,
    switchedAt: Date,
    completedAt: Date,
    rolledBackAt: Date,
  },
  industryLocked: { type: Boolean, default: true },
  industryRevision: { type: Number, default: 0, min: 0 },
  customerRules: {
    vipSpend: { type: Number, min: 0, default: 10000 },
    repeatOrders: { type: Number, min: 2, max: 100, default: 2 },
    inactiveDays: { type: Number, min: 30, max: 730, default: 90 },
    frequentReturnCount: { type: Number, min: 1, max: 100, default: 2 },
    highRtoMinimumOrders: { type: Number, min: 1, max: 100, default: 2 },
    highRtoRate: { type: Number, min: 0.05, max: 1, default: 0.4 },
    highValueCart: { type: Number, min: 0, default: 5000 },
    newCustomerDays: { type: Number, min: 1, max: 180, default: 30 },
  },
  plan: { type: String, enum: PLAN_IDS, default: 'BASIC', index: true },
  license: {
    status: { type: String, enum: LICENSE_STATUSES, default: 'TRIAL' },
    startsAt: { type: Date, default: Date.now },
    trialEndsAt: Date,
    endsAt: Date,
    billingCycle: { type: String, enum: BILLING_CYCLES, default: 'TRIAL' },
    featureOverrides: { type: [String], default: [] },
    disabledFeatures: { type: [String], default: [] },
    limitOverrides: {
      products: { type: Number, min: 0 },
      ordersPerMonth: { type: Number, min: 0 },
    },
    lastPayment: {
      orderId: String,
      paymentId: String,
      amount: Number,
      currency: String,
      paidAt: Date,
    },
    renewalMessage: { type: String, maxlength: 300 },
  },
  festivalCampaign: {
    enabled: { type: Boolean, default: false },
    campaignKey: { type: String, trim: true, lowercase: true, maxlength: 80 },
    preset: { type: String, enum: ['', 'diwali', 'wedding', 'eid', 'christmas', 'valentines', 'black-friday', 'new-year', 'holi'], default: '' },
    title: { type: String, maxlength: 100 },
    badgeText: { type: String, maxlength: 60 },
    couponCode: { type: String, maxlength: 40 },
    startsAt: Date,
    countdownEndsAt: Date,
    effects: { type: Boolean, default: false },
    publishedAt: Date,
    pausedAt: Date,
    updatedAt: Date,
  },
  storefrontDesign: {
    preset: { type: String, default: 'default', maxlength: 40 },
    draftConfig: mongoose.Schema.Types.Mixed,
    publishedConfig: mongoose.Schema.Types.Mixed,
    revision: { type: Number, default: 0, min: 0 },
    updatedAt: Date,
    publishedAt: Date,
    scheduledConfig: mongoose.Schema.Types.Mixed,
    scheduledFor: Date,
    scheduledNote: { type: String, maxlength: 240 },
    scheduledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    scheduledContent: mongoose.Schema.Types.Mixed,
    scheduledContentId: { type: String, trim: true, maxlength: 80 },
    scheduledContentFor: Date,
    scheduledContentNote: { type: String, maxlength: 240 },
    scheduledContentBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    scheduledContentStatus: { type: String, enum: ['SCHEDULED', 'PROCESSING', 'FAILED'] },
    scheduledContentAttempts: { type: Number, min: 0 },
    scheduledContentLeaseUntil: Date,
    scheduledContentLastAttemptAt: Date,
    scheduledContentError: { type: String, maxlength: 500 },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
}, { timestamps: true });

storeSchema.index({ isDefault: 1, status: 1 });
storeSchema.index({ archivedAt: 1, createdAt: -1 });
storeSchema.index({ customDomain: 1 }, { unique: true, sparse: true });
storeSchema.index({ 'license.status': 1, 'license.endsAt': 1 }, { name: 'license_expiry_due' });
storeSchema.index({ 'license.status': 1, 'license.trialEndsAt': 1 }, { name: 'trial_expiry_due' });
storeSchema.index({ 'storefrontDesign.scheduledContentFor': 1, 'storefrontDesign.scheduledContentStatus': 1 }, { name: 'store_content_release_due' });

module.exports = mongoose.model('Store', storeSchema);
module.exports.STORE_STATUSES = STORE_STATUSES;
